In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("diabetes.csv")

In [3]:
data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [4]:
data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [5]:
data.shape

(768, 9)

In [6]:
data.Outcome.unique()

array([1, 0], dtype=int64)

In [7]:
data.DiabetesPedigreeFunction.unique()

array([0.627, 0.351, 0.672, 0.167, 2.288, 0.201, 0.248, 0.134, 0.158,
       0.232, 0.191, 0.537, 1.441, 0.398, 0.587, 0.484, 0.551, 0.254,
       0.183, 0.529, 0.704, 0.388, 0.451, 0.263, 0.205, 0.257, 0.487,
       0.245, 0.337, 0.546, 0.851, 0.267, 0.188, 0.512, 0.966, 0.42 ,
       0.665, 0.503, 1.39 , 0.271, 0.696, 0.235, 0.721, 0.294, 1.893,
       0.564, 0.586, 0.344, 0.305, 0.491, 0.526, 0.342, 0.467, 0.718,
       0.962, 1.781, 0.173, 0.304, 0.27 , 0.699, 0.258, 0.203, 0.855,
       0.845, 0.334, 0.189, 0.867, 0.411, 0.583, 0.231, 0.396, 0.14 ,
       0.391, 0.37 , 0.307, 0.102, 0.767, 0.237, 0.227, 0.698, 0.178,
       0.324, 0.153, 0.165, 0.443, 0.261, 0.277, 0.761, 0.255, 0.13 ,
       0.323, 0.356, 0.325, 1.222, 0.179, 0.262, 0.283, 0.93 , 0.801,
       0.207, 0.287, 0.336, 0.247, 0.199, 0.543, 0.192, 0.588, 0.539,
       0.22 , 0.654, 0.223, 0.759, 0.26 , 0.404, 0.186, 0.278, 0.496,
       0.452, 0.403, 0.741, 0.361, 1.114, 0.457, 0.647, 0.088, 0.597,
       0.532, 0.703, 0.159, 0.268, 0.286, 0.318, 0.272, 0.572, 0.096,
       1.4  , 0.218, 0.085, 0.399, 0.432, 1.189, 0.687, 0.137, 0.637,
       0.833, 0.229, 0.817, 0.204, 0.368, 0.743, 0.722, 0.256, 0.709,
       0.471, 0.495, 0.18 , 0.542, 0.773, 0.678, 0.719, 0.382, 0.319,
       0.19 , 0.956, 0.084, 0.725, 0.299, 0.244, 0.745, 0.615, 1.321,
       0.64 , 0.142, 0.374, 0.383, 0.578, 0.136, 0.395, 0.187, 0.905,
       0.15 , 0.874, 0.236, 0.787, 0.407, 0.605, 0.151, 0.289, 0.355,
       0.29 , 0.375, 0.164, 0.431, 0.742, 0.514, 0.464, 1.224, 1.072,
       0.805, 0.209, 0.666, 0.101, 0.198, 0.652, 2.329, 0.089, 0.645,
       0.238, 0.394, 0.293, 0.479, 0.686, 0.831, 0.582, 0.446, 0.402,
       1.318, 0.329, 1.213, 0.427, 0.282, 0.143, 0.38 , 0.284, 0.249,
       0.926, 0.557, 0.092, 0.655, 1.353, 0.612, 0.2  , 0.226, 0.997,
       0.933, 1.101, 0.078, 0.24 , 1.136, 0.128, 0.422, 0.251, 0.677,
       0.296, 0.454, 0.744, 0.881, 0.28 , 0.259, 0.619, 0.808, 0.34 ,
       0.434, 0.757, 0.613, 0.692, 0.52 , 0.412, 0.84 , 0.839, 0.156,
       0.215, 0.326, 1.391, 0.875, 0.313, 0.433, 0.626, 1.127, 0.315,
       0.345, 0.129, 0.527, 0.197, 0.731, 0.148, 0.123, 0.127, 0.122,
       1.476, 0.166, 0.932, 0.343, 0.893, 0.331, 0.472, 0.673, 0.389,
       0.485, 0.349, 0.279, 0.346, 0.252, 0.243, 0.58 , 0.559, 0.302,
       0.569, 0.378, 0.385, 0.499, 0.306, 0.234, 2.137, 1.731, 0.545,
       0.225, 0.816, 0.528, 0.509, 1.021, 0.821, 0.947, 1.268, 0.221,
       0.66 , 0.239, 0.949, 0.444, 0.463, 0.803, 1.6  , 0.944, 0.196,
       0.241, 0.161, 0.135, 0.376, 1.191, 0.702, 0.674, 1.076, 0.534,
       1.095, 0.554, 0.624, 0.219, 0.507, 0.561, 0.421, 0.516, 0.264,
       0.328, 0.233, 0.108, 1.138, 0.147, 0.727, 0.435, 0.497, 0.23 ,
       0.955, 2.42 , 0.658, 0.33 , 0.51 , 0.285, 0.415, 0.381, 0.832,
       0.498, 0.212, 0.364, 1.001, 0.46 , 0.733, 0.416, 0.705, 1.022,
       0.269, 0.6  , 0.571, 0.607, 0.17 , 0.21 , 0.126, 0.711, 0.466,
       0.162, 0.419, 0.63 , 0.365, 0.536, 1.159, 0.629, 0.292, 0.145,
       1.144, 0.174, 0.547, 0.163, 0.738, 0.314, 0.968, 0.409, 0.297,
       0.525, 0.154, 0.771, 0.107, 0.493, 0.717, 0.917, 0.501, 1.251,
       0.735, 0.804, 0.661, 0.549, 0.825, 0.423, 1.034, 0.16 , 0.341,
       0.68 , 0.591, 0.3  , 0.121, 0.502, 0.401, 0.601, 0.748, 0.338,
       0.43 , 0.892, 0.813, 0.693, 0.575, 0.371, 0.206, 0.417, 1.154,
       0.925, 0.175, 1.699, 0.682, 0.194, 0.4  , 0.1  , 1.258, 0.482,
       0.138, 0.593, 0.878, 0.157, 1.282, 0.141, 0.246, 1.698, 1.461,
       0.347, 0.362, 0.393, 0.144, 0.732, 0.115, 0.465, 0.649, 0.871,
       0.149, 0.695, 0.303, 0.61 , 0.73 , 0.447, 0.455, 0.133, 0.155,
       1.162, 1.292, 0.182, 1.394, 0.217, 0.631, 0.88 , 0.614, 0.332,
       0.366, 0.181, 0.828, 0.335, 0.856, 0.886, 0.439, 0.253, 0.598,
       0.904, 0.483, 0.565, 0.118, 0.177, 0.176, 0.295, 0.441, 0.352,
       0.826, 0.97 , 0.595, 0.317, 0.265, 0.646, 0.426, 0.56 , 0.515,
       0.453, 0.785, 0.734, 1.174, 0.488, 0.358, 1.096, 0.408, 1.182,
       0.222, 1.057, 0.766, 0.171])

In [8]:
data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [9]:
data.isna

<bound method DataFrame.isna of      Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6
1              1       85             66             29        0  26.6
2              8      183             64              0        0  23.3
3              1       89             66             23       94  28.1
4              0      137             40             35      168  43.1
..           ...      ...            ...            ...      ...   ...
763           10      101             76             48      180  32.9
764            2      122             70             27        0  36.8
765            5      121             72             23      112  26.2
766            1      126             60              0        0  30.1
767            1       93             70             31        0  30.4

     DiabetesPedigreeFunction  Age  Outcome
0                       0.627   50        1
1                       0.351   31        0
2                       0.672   32        1
3                       0.167   21        0
4                       2.288   33        1
..                        ...  ...      ...
763                     0.171   63        0
764                     0.340   27        0
765                     0.245   30        0
766                     0.349   47        1
767                     0.315   23        0

[768 rows x 9 columns]>

In [10]:
data.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [11]:
data.duplicated().sum()

0

In [12]:
x = data.drop("Outcome", axis=1)

In [13]:
x

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33
...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63
764,2,122,70,27,0,36.8,0.340,27
765,5,121,72,23,112,26.2,0.245,30
766,1,126,60,0,0,30.1,0.349,47
767,1,93,70,31,0,30.4,0.315,23

In [14]:
y = data.Outcome

In [15]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=45456,test_size=0.20)

In [17]:
x_train

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
26,7,147,76,0,0,39.4,0.257,43
432,1,80,74,11,60,30.0,0.527,22
269,2,146,0,0,0,27.5,0.240,28
668,6,98,58,33,190,34.0,0.430,43
682,0,95,64,39,105,44.6,0.366,22
...,...,...,...,...,...,...,...,...
589,0,73,0,0,0,21.1,0.342,25
31,3,158,76,36,245,31.6,0.851,28
44,7,159,64,0,0,27.4,0.294,40
354,3,90,78,0,0,42.7,0.559,21
387,8,105,100,36,0,43.3,0.239,45

In [18]:
x_test

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
68,1,95,66,13,38,19.6,0.334,25
322,0,124,70,20,0,27.4,0.254,36
98,6,93,50,30,64,28.7,0.356,23
763,10,101,76,48,180,32.9,0.171,63
570,3,78,70,0,0,32.5,0.270,39
...,...,...,...,...,...,...,...,...
275,2,100,70,52,57,40.5,0.677,25
162,0,114,80,34,285,44.2,0.167,27
639,1,100,74,12,46,19.5,0.149,28
413,1,143,74,22,61,26.2,0.256,21
282,7,133,88,15,155,32.4,0.262,37

In [19]:
y_test

68     0
322    1
98     0
763    0
570    0
      ..
275    0
162    0
639    0
413    0
282    0
Name: Outcome, Length: 154, dtype: int64

In [20]:
y_train

26     1
432    0
269    1
668    0
682    0
      ..
589    0
31     1
44     0
354    0
387    1
Name: Outcome, Length: 614, dtype: int64

In [21]:
from sklearn.linear_model import LogisticRegression

In [22]:
lr = LogisticRegression()

In [23]:
lr.fit(x_train,y_train)

C:\Users\User\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [24]:
y_pred_train = lr.predict(x_train)

In [25]:
from sklearn.metrics import accuracy_score,confusion_matrix
print(confusion_matrix(y_train,y_pred_train))
print(confusion_matrix(y_train,y_pred_train))

[[353  47]
 [ 89 125]]
[[353  47]
 [ 89 125]]

In [26]:
from sklearn.metrics import classification_report
print(classification_report(y_train,y_pred_train))

              precision    recall  f1-score   support

           0       0.80      0.88      0.84       400
           1       0.73      0.58      0.65       214

    accuracy                           0.78       614
   macro avg       0.76      0.73      0.74       614
weighted avg       0.77      0.78      0.77       614

In [27]:
y_pred_test = lr.predict(x_test)

In [28]:
y_pred_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [29]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred_test))

              precision    recall  f1-score   support

           0       0.78      0.87      0.82       100
           1       0.70      0.56      0.62        54

    accuracy                           0.76       154
   macro avg       0.74      0.71      0.72       154
weighted avg       0.75      0.76      0.75       154

In [30]:
no_diab = data[data.Outcome == 0] . sample(268)

In [31]:
no_diab

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
156,2,99,52,15,94,24.6,0.637,21,0
58,0,146,82,0,0,40.5,1.781,44,0
620,2,112,86,42,160,38.4,0.246,28,0
723,5,117,86,30,105,39.1,0.251,42,0
714,3,102,74,0,0,29.5,0.121,32,0
...,...,...,...,...,...,...,...,...,...
705,6,80,80,36,0,39.8,0.177,28,0
318,3,115,66,39,140,38.1,0.150,28,0
54,7,150,66,42,342,34.7,0.718,42,0
74,1,79,75,30,0,32.0,0.396,22,0
489,8,194,80,0,0,26.1,0.551,67,0

In [32]:
yes_diab = data[data.Outcome ==1]

In [33]:
yes_diab

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
2,8,183,64,0,0,23.3,0.672,32,1
4,0,137,40,35,168,43.1,2.288,33,1
6,3,78,50,32,88,31.0,0.248,26,1
8,2,197,70,45,543,30.5,0.158,53,1
...,...,...,...,...,...,...,...,...,...
755,1,128,88,39,110,36.5,1.057,37,1
757,0,123,72,0,0,36.3,0.258,52,1
759,6,190,92,0,0,35.5,0.278,66,1
761,9,170,74,31,0,44.0,0.403,43,1
766,1,126,60,0,0,30.1,0.349,47,1

In [34]:
new_data = pd.concat([no_diab,yes_diab])

In [35]:
new_data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
156,2,99,52,15,94,24.6,0.637,21,0
58,0,146,82,0,0,40.5,1.781,44,0
620,2,112,86,42,160,38.4,0.246,28,0
723,5,117,86,30,105,39.1,0.251,42,0
714,3,102,74,0,0,29.5,0.121,32,0
...,...,...,...,...,...,...,...,...,...
755,1,128,88,39,110,36.5,1.057,37,1
757,0,123,72,0,0,36.3,0.258,52,1
759,6,190,92,0,0,35.5,0.278,66,1
761,9,170,74,31,0,44.0,0.403,43,1
766,1,126,60,0,0,30.1,0.349,47,1

In [36]:
new_data.Outcome.unique()

array([0, 1], dtype=int64)

In [37]:
x = new_data.drop("Outcome", axis=1)
x

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
156,2,99,52,15,94,24.6,0.637,21
58,0,146,82,0,0,40.5,1.781,44
620,2,112,86,42,160,38.4,0.246,28
723,5,117,86,30,105,39.1,0.251,42
714,3,102,74,0,0,29.5,0.121,32
...,...,...,...,...,...,...,...,...
755,1,128,88,39,110,36.5,1.057,37
757,0,123,72,0,0,36.3,0.258,52
759,6,190,92,0,0,35.5,0.278,66
761,9,170,74,31,0,44.0,0.403,43
766,1,126,60,0,0,30.1,0.349,47

In [38]:
x

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
156,2,99,52,15,94,24.6,0.637,21
58,0,146,82,0,0,40.5,1.781,44
620,2,112,86,42,160,38.4,0.246,28
723,5,117,86,30,105,39.1,0.251,42
714,3,102,74,0,0,29.5,0.121,32
...,...,...,...,...,...,...,...,...
755,1,128,88,39,110,36.5,1.057,37
757,0,123,72,0,0,36.3,0.258,52
759,6,190,92,0,0,35.5,0.278,66
761,9,170,74,31,0,44.0,0.403,43
766,1,126,60,0,0,30.1,0.349,47

In [39]:
y= new_data.Outcome

In [40]:
y

156    0
58     0
620    0
723    0
714    0
      ..
755    1
757    1
759    1
761    1
766    1
Name: Outcome, Length: 536, dtype: int64

In [41]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=45456,test_size=0.20)

In [42]:
x_train

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
8,2,197,70,45,543,30.5,0.158,53
150,1,136,74,50,204,37.4,0.399,24
355,9,165,88,0,0,30.4,0.302,49
741,3,102,44,20,94,30.8,0.400,26
51,1,101,50,15,36,24.2,0.526,26
...,...,...,...,...,...,...,...,...
170,6,102,82,0,0,30.8,0.180,36
558,11,103,68,40,0,46.2,0.126,42
728,2,175,88,0,0,22.9,0.326,22
227,3,162,52,38,0,37.2,0.652,24
309,2,124,68,28,205,32.9,0.875,30

In [43]:
x_test

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
532,1,86,66,52,65,41.3,0.917,29
675,6,195,70,0,0,30.9,0.328,31
493,4,125,70,18,122,28.9,1.144,45
156,2,99,52,15,94,24.6,0.637,21
114,7,160,54,32,175,30.5,0.588,39
...,...,...,...,...,...,...,...,...
271,2,108,62,32,56,25.2,0.128,21
13,1,189,60,23,846,30.1,0.398,59
651,1,117,60,23,106,33.8,0.466,27
545,8,186,90,35,225,34.5,0.423,37
236,7,181,84,21,192,35.9,0.586,51

In [44]:
y_train

8      1
150    0
355    1
741    0
51     0
      ..
170    1
558    0
728    0
227    1
309    1
Name: Outcome, Length: 428, dtype: int64

In [45]:
y_test

532    0
675    1
493    1
156    0
114    1
      ..
271    0
13     1
651    0
545    1
236    1
Name: Outcome, Length: 108, dtype: int64

In [46]:
from sklearn.linear_model import LogisticRegression

In [47]:
lr = LogisticRegression()

In [48]:
lr.fit(x_train,y_train)

C:\Users\User\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [49]:
y_pred_train = lr.predict(x_train)

In [50]:
from sklearn.metrics import classification_report
print(classification_report(y_train,y_pred_train))

              precision    recall  f1-score   support

           0       0.73      0.77      0.75       213
           1       0.76      0.73      0.74       215

    accuracy                           0.75       428
   macro avg       0.75      0.75      0.75       428
weighted avg       0.75      0.75      0.75       428

In [51]:
from sklearn.metrics import accuracy_score,confusion_matrix
print(confusion_matrix(y_train,y_pred_train))
print(confusion_matrix(y_train,y_pred_train))

[[163  50]
 [ 59 156]]
[[163  50]
 [ 59 156]]

In [52]:
from sklearn.metrics import accuracy_score

In [53]:
print(accuracy_score(y_train,y_pred_train))

0.7453271028037384

In [54]:
from sklearn.metrics import accuracy_score,confusion_matrix
print(confusion_matrix(y_train,y_pred_train))
print(confusion_matrix(y_train,y_pred_train))

[[163  50]
 [ 59 156]]
[[163  50]
 [ 59 156]]

In [55]:
y_pred_test = lr.predict(x_test)

In [56]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred_test))

              precision    recall  f1-score   support

           0       0.80      0.82      0.81        55
           1       0.81      0.79      0.80        53

    accuracy                           0.81       108
   macro avg       0.81      0.81      0.81       108
weighted avg       0.81      0.81      0.81       108

In [57]:
def predict_diabetes(inputs):
    return lr.predict(inputs)

In [58]:
inputs = x.sample(5)

In [59]:
inputs

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
357,13,129,0,30,0,39.9,0.569,44
48,7,103,66,32,0,39.1,0.344,31
122,2,107,74,30,100,33.6,0.404,23
316,3,99,80,11,64,19.3,0.284,30
586,8,143,66,0,0,34.9,0.129,41

In [60]:
predict_diabetes(inputs)

array([1, 1, 0, 0, 1], dtype=int64)

In [61]:
new_data.iloc[207]

Pregnancies                  11.00
Glucose                     138.00
BloodPressure                76.00
SkinThickness                 0.00
Insulin                       0.00
BMI                          33.20
DiabetesPedigreeFunction      0.42
Age                          35.00
Outcome                       0.00
Name: 36, dtype: float64

In [170]:
import pickle
pickle.dump(lr, open('binary_logistic_regression_model.sav','wb'))

In [62]:
data= pd.read_csv("customer_churn_data.csv")

In [63]:
import pandas as pd

In [64]:
data= pd.read_csv("customer_churn_data.csv")

In [65]:
data.shape

(5880, 21)

In [66]:
data.head

<bound method NDFrame.head of      customerID  gender  SeniorCitizen Partner Dependents  tenure  \
0      CUST0000    Male              0      No        Yes      23
1      CUST0001  Female              0     Yes         No      43
2      CUST0002    Male              1      No         No      51
3      CUST0003    Male              1      No         No      72
4      CUST0004    Male              1      No         No      25
...         ...     ...            ...     ...        ...     ...
5875   CUST5875    Male              0     Yes        Yes      71
5876   CUST5876    Male              0      No         No      22
5877   CUST5877  Female              0      No         No      68
5878   CUST5878  Female              0     Yes        Yes      14
5879   CUST5879  Female              1     Yes         No      23

     PhoneService     MultipleLines InternetService       OnlineSecurity  ...  \
0              No  No phone service              No  No internet service  ...
1              No  No phone service             DSL                  Yes  ...
2             Yes                No             DSL                   No  ...
3             Yes               Yes             DSL                  Yes  ...
4             Yes               Yes             DSL                   No  ...
...           ...               ...             ...                  ...  ...
5875          Yes                No             DSL                  Yes  ...
5876          Yes               Yes             DSL                   No  ...
5877           No  No phone service     Fiber optic                  Yes  ...
5878           No  No phone service     Fiber optic                  Yes  ...
5879          Yes                No              No  No internet service  ...

         DeviceProtection          TechSupport          StreamingTV  \
0     No internet service  No internet service  No internet service
1                     Yes                   No                  Yes
2                     Yes                  Yes                   No
3                     Yes                   No                   No
4                      No                  Yes                   No
...                   ...                  ...                  ...
5875                   No                  Yes                   No
5876                  Yes                  Yes                   No
5877                  Yes                  Yes                  Yes
5878                  Yes                  Yes                  Yes
5879  No internet service  No internet service  No internet service

          StreamingMovies        Contract PaperlessBilling     PaymentMethod  \
0     No internet service  Month-to-month              Yes     Bank transfer
1                      No  Month-to-month               No      Mailed check
2                      No        One year               No  Electronic check
3                      No  Month-to-month               No       Credit card
4                     Yes  Month-to-month               No  Electronic check
...                   ...             ...              ...               ...
5875                   No  Month-to-month              Yes      Mailed check
5876                  Yes        One year               No      Mailed check
5877                   No        One year              Yes     Bank transfer
5878                  Yes  Month-to-month              Yes      Mailed check
5879  No internet service  Month-to-month               No      Mailed check

     MonthlyCharges  TotalCharges  Churn
0             49.85       1146.55     No
1            100.70       4330.10    Yes
2             97.33       4963.83    Yes
3            101.38       7299.36     No
4             52.22       1305.50    Yes
...             ...           ...    ...
5875          74.21       5268.91     No
5876          65.43       1439.46    Yes
5877          59.78       4065.04     No
5878          91.88       1286.32     No
5879          25.45        585.35    Yes

[5880 rows x 21 columns]>

In [67]:
data.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,CUST0000,Male,0,No,Yes,23,No,No phone service,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,Yes,Bank transfer,49.85,1146.55,No
1,CUST0001,Female,0,Yes,No,43,No,No phone service,DSL,Yes,...,Yes,No,Yes,No,Month-to-month,No,Mailed check,100.70,4330.10,Yes
2,CUST0002,Male,1,No,No,51,Yes,No,DSL,No,...,Yes,Yes,No,No,One year,No,Electronic check,97.33,4963.83,Yes
3,CUST0003,Male,1,No,No,72,Yes,Yes,DSL,Yes,...,Yes,No,No,No,Month-to-month,No,Credit card,101.38,7299.36,No
4,CUST0004,Male,1,No,No,25,Yes,Yes,DSL,No,...,No,Yes,No,Yes,Month-to-month,No,Electronic check,52.22,1305.50,Yes

In [68]:
data.gender.unique()

array(['Male', 'Female'], dtype=object)

In [69]:
data.SeniorCitizen.unique()

array([0, 1], dtype=int64)

In [70]:
data.Partner.unique()

array(['No', 'Yes'], dtype=object)

In [71]:
data.tenure.unique()

array([23, 43, 51, 72, 25, 35, 17, 18, 27, 15, 69, 42, 34, 48,  8, 10,  5,
       26, 62, 13,  9, 20, 57, 24, 33, 60, 64, 30, 14, 19, 71, 59, 67, 44,
       32, 11,  2, 68, 40, 46,  4, 38, 63, 29, 70, 52, 55, 66, 31, 61, 36,
       37, 47, 22, 39, 58,  7, 65,  6, 45,  1, 56, 21, 16, 49, 41,  3, 12,
       53, 28, 50, 54], dtype=int64)

In [72]:
data.PhoneService.unique()

array(['No', 'Yes'], dtype=object)

In [73]:
data.MultipleLines.unique()

array(['No phone service', 'No', 'Yes'], dtype=object)

In [74]:
data.MultipleLines.replace('No phone service',"No", inplace = True)

C:\Users\User\AppData\Local\Temp\ipykernel_15276\1344902159.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data.MultipleLines.replace('No phone service',"No", inplace = True)

In [75]:
data.MultipleLines.unique()

array(['No', 'Yes'], dtype=object)

In [76]:
data.InternetService.unique()

array(['No', 'DSL', 'Fiber optic'], dtype=object)

In [77]:
data.OnlineSecurity.unique()

array(['No internet service', 'Yes', 'No'], dtype=object)

In [78]:
data.OnlineSecurity.replace('No internet service', "No", inplace= True)

C:\Users\User\AppData\Local\Temp\ipykernel_15276\3607027636.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data.OnlineSecurity.replace('No internet service', "No", inplace= True)

In [79]:
data.OnlineSecurity.unique()

array(['No', 'Yes'], dtype=object)

In [80]:
data.OnlineBackup.unique()

array(['No internet service', 'No', 'Yes'], dtype=object)

In [81]:
data.OnlineBackup.replace('No internet service','No', inplace = True)

C:\Users\User\AppData\Local\Temp\ipykernel_15276\2110033839.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data.OnlineBackup.replace('No internet service','No', inplace = True)

In [82]:
data.OnlineBackup.unique()

array(['No', 'Yes'], dtype=object)

In [83]:
data.DeviceProtection.unique()

array(['No internet service', 'Yes', 'No'], dtype=object)

In [84]:
data.DeviceProtection.replace('No internet service', 'No', inplace = True)

C:\Users\User\AppData\Local\Temp\ipykernel_15276\1152658549.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data.DeviceProtection.replace('No internet service', 'No', inplace = True)

In [85]:
data.DeviceProtection.unique()

array(['No', 'Yes'], dtype=object)

In [86]:
data.TechSupport.unique()

array(['No internet service', 'No', 'Yes'], dtype=object)

In [87]:
data.TechSupport.replace ('No internet service', 'No', inplace= True)

C:\Users\User\AppData\Local\Temp\ipykernel_15276\1746537711.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data.TechSupport.replace ('No internet service', 'No', inplace= True)

In [88]:
data.TechSupport.unique()

array(['No', 'Yes'], dtype=object)

In [89]:
data.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,CUST0000,Male,0,No,Yes,23,No,No,No,No,...,No,No,No internet service,No internet service,Month-to-month,Yes,Bank transfer,49.85,1146.55,No
1,CUST0001,Female,0,Yes,No,43,No,No,DSL,Yes,...,Yes,No,Yes,No,Month-to-month,No,Mailed check,100.70,4330.10,Yes
2,CUST0002,Male,1,No,No,51,Yes,No,DSL,No,...,Yes,Yes,No,No,One year,No,Electronic check,97.33,4963.83,Yes
3,CUST0003,Male,1,No,No,72,Yes,Yes,DSL,Yes,...,Yes,No,No,No,Month-to-month,No,Credit card,101.38,7299.36,No
4,CUST0004,Male,1,No,No,25,Yes,Yes,DSL,No,...,No,Yes,No,Yes,Month-to-month,No,Electronic check,52.22,1305.50,Yes

In [90]:
data.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [91]:
data.StreamingTV.unique()

array(['No internet service', 'Yes', 'No'], dtype=object)

In [92]:
data.StreamingTV.replace('No internet service', 'No', inplace = True)

C:\Users\User\AppData\Local\Temp\ipykernel_15276\907287942.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data.StreamingTV.replace('No internet service', 'No', inplace = True)

In [93]:
data.StreamingTV.unique()

array(['No', 'Yes'], dtype=object)

In [94]:
data.Contract.unique()

array(['Month-to-month', 'One year', 'Two year'], dtype=object)

In [95]:
data.PaperlessBilling.unique()

array(['Yes', 'No'], dtype=object)

In [96]:
data.PaymentMethod.unique()

array(['Bank transfer', 'Mailed check', 'Electronic check', 'Credit card'],
      dtype=object)

In [97]:
data.MonthlyCharges.unique()

array([ 49.85, 100.7 ,  97.33, ...,  34.06,  74.21,  65.43])

In [98]:
data.Churn.unique()

array(['No', 'Yes'], dtype=object)

In [99]:
data[["PaymentMethod", "InternetService", "Contract"]]

         PaymentMethod InternetService        Contract
0        Bank transfer              No  Month-to-month
1         Mailed check             DSL  Month-to-month
2     Electronic check             DSL        One year
3          Credit card             DSL  Month-to-month
4     Electronic check             DSL  Month-to-month
...                ...             ...             ...
5875      Mailed check             DSL  Month-to-month
5876      Mailed check             DSL        One year
5877     Bank transfer     Fiber optic        One year
5878      Mailed check     Fiber optic  Month-to-month
5879      Mailed check              No  Month-to-month

[5880 rows x 3 columns]

In [100]:
data.InternetService.replace(['DSL','Fiber optic'], 'Yes', inplace = True)

C:\Users\User\AppData\Local\Temp\ipykernel_15276\2380393183.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data.InternetService.replace(['DSL','Fiber optic'], 'Yes', inplace = True)

In [101]:
data.InternetService.unique()

array(['No', 'Yes'], dtype=object)

In [102]:
data.InternetService.replace(['DSL','Fiber optic'] , 'Yes', inplace = True)

In [103]:
data.InternetService.unique()

array(['No', 'Yes'], dtype=object)

In [104]:
pd.get_dummies(data, columns= ['PaymentMethod', 'Contract'], drop_first=True)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingMovies,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,PaymentMethod_Credit card,PaymentMethod_Electronic check,PaymentMethod_Mailed check,Contract_One year,Contract_Two year
0,CUST0000,Male,0,No,Yes,23,No,No,No,No,...,No internet service,Yes,49.85,1146.55,No,False,False,False,False,False
1,CUST0001,Female,0,Yes,No,43,No,No,Yes,Yes,...,No,No,100.70,4330.10,Yes,False,False,True,False,False
2,CUST0002,Male,1,No,No,51,Yes,No,Yes,No,...,No,No,97.33,4963.83,Yes,False,True,False,True,False
3,CUST0003,Male,1,No,No,72,Yes,Yes,Yes,Yes,...,No,No,101.38,7299.36,No,True,False,False,False,False
4,CUST0004,Male,1,No,No,25,Yes,Yes,Yes,No,...,Yes,No,52.22,1305.50,Yes,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5875,CUST5875,Male,0,Yes,Yes,71,Yes,No,Yes,Yes,...,No,Yes,74.21,5268.91,No,False,False,True,False,False
5876,CUST5876,Male,0,No,No,22,Yes,Yes,Yes,No,...,Yes,No,65.43,1439.46,Yes,False,False,True,True,False
5877,CUST5877,Female,0,No,No,68,No,No,Yes,Yes,...,No,Yes,59.78,4065.04,No,False,False,False,True,False
5878,CUST5878,Female,0,Yes,Yes,14,No,No,Yes,Yes,...,Yes,Yes,91.88,1286.32,No,False,False,True,False,False
5879,CUST5879,Female,1,Yes,No,23,Yes,No,No,No,...,No internet service,No,25.45,585.35,Yes,False,False,True,False,False

In [105]:
data.PaymentMethod.unique()

array(['Bank transfer', 'Mailed check', 'Electronic check', 'Credit card'],
      dtype=object)

In [106]:
pd.get_dummies (data, columns = ['PaymentMethod', 'Contract'], drop_first= True)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingMovies,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,PaymentMethod_Credit card,PaymentMethod_Electronic check,PaymentMethod_Mailed check,Contract_One year,Contract_Two year
0,CUST0000,Male,0,No,Yes,23,No,No,No,No,...,No internet service,Yes,49.85,1146.55,No,False,False,False,False,False
1,CUST0001,Female,0,Yes,No,43,No,No,Yes,Yes,...,No,No,100.70,4330.10,Yes,False,False,True,False,False
2,CUST0002,Male,1,No,No,51,Yes,No,Yes,No,...,No,No,97.33,4963.83,Yes,False,True,False,True,False
3,CUST0003,Male,1,No,No,72,Yes,Yes,Yes,Yes,...,No,No,101.38,7299.36,No,True,False,False,False,False
4,CUST0004,Male,1,No,No,25,Yes,Yes,Yes,No,...,Yes,No,52.22,1305.50,Yes,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5875,CUST5875,Male,0,Yes,Yes,71,Yes,No,Yes,Yes,...,No,Yes,74.21,5268.91,No,False,False,True,False,False
5876,CUST5876,Male,0,No,No,22,Yes,Yes,Yes,No,...,Yes,No,65.43,1439.46,Yes,False,False,True,True,False
5877,CUST5877,Female,0,No,No,68,No,No,Yes,Yes,...,No,Yes,59.78,4065.04,No,False,False,False,True,False
5878,CUST5878,Female,0,Yes,Yes,14,No,No,Yes,Yes,...,Yes,Yes,91.88,1286.32,No,False,False,True,False,False
5879,CUST5879,Female,1,Yes,No,23,Yes,No,No,No,...,No internet service,No,25.45,585.35,Yes,False,False,True,False,False

In [107]:
data.gender.replace(['Male', 'Female'], [1,0], inplace=True)

C:\Users\User\AppData\Local\Temp\ipykernel_15276\2121630364.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data.gender.replace(['Male', 'Female'], [1,0], inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_15276\2121630364.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data.gender.replace(['Male', 'Female'], [1,0], inplace=True)

In [108]:
data.gender.unique()

array([1, 0], dtype=int64)

In [109]:
data.Dependents.replace(['Yes','No'], [1,0], inplace=True)

C:\Users\User\AppData\Local\Temp\ipykernel_15276\2366383061.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data.Dependents.replace(['Yes','No'], [1,0], inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_15276\2366383061.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data.Dependents.replace(['Yes','No'], [1,0], inplace=True)

In [110]:
data.Dependents.unique()

array([1, 0], dtype=int64)

In [111]:
data.PhoneService.replace(['Yes','No'], [1,0], inplace=True)

C:\Users\User\AppData\Local\Temp\ipykernel_15276\3209330826.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data.PhoneService.replace(['Yes','No'], [1,0], inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_15276\3209330826.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data.PhoneService.replace(['Yes','No'], [1,0], inplace=True)

In [112]:
data.PhoneService.unique()

array([0, 1], dtype=int64)

In [113]:
data.MultipleLines.replace(['Yes','No'], [1,0], inplace=True)

C:\Users\User\AppData\Local\Temp\ipykernel_15276\221399730.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data.MultipleLines.replace(['Yes','No'], [1,0], inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_15276\221399730.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data.MultipleLines.replace(['Yes','No'], [1,0], inplace=True)

In [114]:
data.MultipleLines.unique

<bound method Series.unique of 0       0
1       0
2       0
3       1
4       1
       ..
5875    0
5876    1
5877    0
5878    0
5879    0
Name: MultipleLines, Length: 5880, dtype: int64>

In [115]:
data.InternetService.replace(['Yes','No'], [1,0], inplace=True)
data.InternetService.unique()

C:\Users\User\AppData\Local\Temp\ipykernel_15276\274451823.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data.InternetService.replace(['Yes','No'], [1,0], inplace=True)

array([0, 1], dtype=int64)

In [116]:
data.OnlineSecurity.replace(['Yes','No'], [1,0], inplace=True)
data.OnlineSecurity.unique()

C:\Users\User\AppData\Local\Temp\ipykernel_15276\2206517140.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data.OnlineSecurity.replace(['Yes','No'], [1,0], inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_15276\2206517140.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data.OnlineSecurity.replace(['Yes','No'], [1,0], inplace=True)

array([0, 1], dtype=int64)

In [117]:
data.OnlineBackup.replace(['Yes','No'], [1,0], inplace=True)
data.OnlineBackup.unique()

C:\Users\User\AppData\Local\Temp\ipykernel_15276\2276446672.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data.OnlineBackup.replace(['Yes','No'], [1,0], inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_15276\2276446672.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data.OnlineBackup.replace(['Yes','No'], [1,0], inplace=True)

array([0, 1], dtype=int64)

In [118]:
data.DeviceProtection.replace(['Yes','No'], [1,0], inplace=True)
data.DeviceProtection.unique()

C:\Users\User\AppData\Local\Temp\ipykernel_15276\443688142.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data.DeviceProtection.replace(['Yes','No'], [1,0], inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_15276\443688142.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data.DeviceProtection.replace(['Yes','No'], [1,0], inplace=True)

array([0, 1], dtype=int64)

In [119]:
data.TechSupport.replace(['Yes','No'], [1,0], inplace=True)
data.TechSupport.unique()

C:\Users\User\AppData\Local\Temp\ipykernel_15276\3710010685.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data.TechSupport.replace(['Yes','No'], [1,0], inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_15276\3710010685.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data.TechSupport.replace(['Yes','No'], [1,0], inplace=True)

array([0, 1], dtype=int64)

In [120]:
data

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,CUST0000,1,0,No,1,23,0,0,0,0,...,0,0,No,No internet service,Month-to-month,Yes,Bank transfer,49.85,1146.55,No
1,CUST0001,0,0,Yes,0,43,0,0,1,1,...,1,0,Yes,No,Month-to-month,No,Mailed check,100.70,4330.10,Yes
2,CUST0002,1,1,No,0,51,1,0,1,0,...,1,1,No,No,One year,No,Electronic check,97.33,4963.83,Yes
3,CUST0003,1,1,No,0,72,1,1,1,1,...,1,0,No,No,Month-to-month,No,Credit card,101.38,7299.36,No
4,CUST0004,1,1,No,0,25,1,1,1,0,...,0,1,No,Yes,Month-to-month,No,Electronic check,52.22,1305.50,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5875,CUST5875,1,0,Yes,1,71,1,0,1,1,...,0,1,No,No,Month-to-month,Yes,Mailed check,74.21,5268.91,No
5876,CUST5876,1,0,No,0,22,1,1,1,0,...,1,1,No,Yes,One year,No,Mailed check,65.43,1439.46,Yes
5877,CUST5877,0,0,No,0,68,0,0,1,1,...,1,1,Yes,No,One year,Yes,Bank transfer,59.78,4065.04,No
5878,CUST5878,0,0,Yes,1,14,0,0,1,1,...,1,1,Yes,Yes,Month-to-month,Yes,Mailed check,91.88,1286.32,No
5879,CUST5879,0,1,Yes,0,23,1,0,0,0,...,0,0,No,No internet service,Month-to-month,No,Mailed check,25.45,585.35,Yes

In [121]:
data.StreamingMovies.replace(['Yes','No'], [1,0], inplace=True)
data.StreamingMovies.unique()

C:\Users\User\AppData\Local\Temp\ipykernel_15276\2696820525.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data.StreamingMovies.replace(['Yes','No'], [1,0], inplace=True)

array(['No internet service', 0, 1], dtype=object)

In [122]:
data.StreamingTV.replace('No internet service', 'No', inplace = True)

C:\Users\User\AppData\Local\Temp\ipykernel_15276\907287942.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data.StreamingTV.replace('No internet service', 'No', inplace = True)

In [123]:
data.StreamingMovies.unique()

array(['No internet service', 0, 1], dtype=object)

In [124]:
data.StreamingMovies.replace('No internet service',0 , inplace = True)

C:\Users\User\AppData\Local\Temp\ipykernel_15276\4015579839.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data.StreamingMovies.replace('No internet service',0 , inplace = True)

In [125]:
data.StreamingMovies.unique()

array([0, 1], dtype=int64)

In [126]:
data.PaperlessBilling.replace(['Yes','No'], [1,0], inplace=True)
data.PaperlessBilling.unique()

C:\Users\User\AppData\Local\Temp\ipykernel_15276\1652557334.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data.PaperlessBilling.replace(['Yes','No'], [1,0], inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_15276\1652557334.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data.PaperlessBilling.replace(['Yes','No'], [1,0], inplace=True)

array([1, 0], dtype=int64)

In [127]:
data

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,CUST0000,1,0,No,1,23,0,0,0,0,...,0,0,No,0,Month-to-month,1,Bank transfer,49.85,1146.55,No
1,CUST0001,0,0,Yes,0,43,0,0,1,1,...,1,0,Yes,0,Month-to-month,0,Mailed check,100.70,4330.10,Yes
2,CUST0002,1,1,No,0,51,1,0,1,0,...,1,1,No,0,One year,0,Electronic check,97.33,4963.83,Yes
3,CUST0003,1,1,No,0,72,1,1,1,1,...,1,0,No,0,Month-to-month,0,Credit card,101.38,7299.36,No
4,CUST0004,1,1,No,0,25,1,1,1,0,...,0,1,No,1,Month-to-month,0,Electronic check,52.22,1305.50,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5875,CUST5875,1,0,Yes,1,71,1,0,1,1,...,0,1,No,0,Month-to-month,1,Mailed check,74.21,5268.91,No
5876,CUST5876,1,0,No,0,22,1,1,1,0,...,1,1,No,1,One year,0,Mailed check,65.43,1439.46,Yes
5877,CUST5877,0,0,No,0,68,0,0,1,1,...,1,1,Yes,0,One year,1,Bank transfer,59.78,4065.04,No
5878,CUST5878,0,0,Yes,1,14,0,0,1,1,...,1,1,Yes,1,Month-to-month,1,Mailed check,91.88,1286.32,No
5879,CUST5879,0,1,Yes,0,23,1,0,0,0,...,0,0,No,0,Month-to-month,0,Mailed check,25.45,585.35,Yes

In [128]:
data.Partner.replace(['Yes','No'], [1,0], inplace=True)
data.Partner.unique()

C:\Users\User\AppData\Local\Temp\ipykernel_15276\4236914081.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data.Partner.replace(['Yes','No'], [1,0], inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_15276\4236914081.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data.Partner.replace(['Yes','No'], [1,0], inplace=True)

array([0, 1], dtype=int64)

In [129]:
data.StreamingTV.replace(['Yes','No'], [1,0], inplace=True)
data.StreamingTV.unique()

C:\Users\User\AppData\Local\Temp\ipykernel_15276\1492960065.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data.StreamingTV.replace(['Yes','No'], [1,0], inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_15276\1492960065.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data.StreamingTV.replace(['Yes','No'], [1,0], inplace=True)

array([0, 1], dtype=int64)

In [130]:
data

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,CUST0000,1,0,0,1,23,0,0,0,0,...,0,0,0,0,Month-to-month,1,Bank transfer,49.85,1146.55,No
1,CUST0001,0,0,1,0,43,0,0,1,1,...,1,0,1,0,Month-to-month,0,Mailed check,100.70,4330.10,Yes
2,CUST0002,1,1,0,0,51,1,0,1,0,...,1,1,0,0,One year,0,Electronic check,97.33,4963.83,Yes
3,CUST0003,1,1,0,0,72,1,1,1,1,...,1,0,0,0,Month-to-month,0,Credit card,101.38,7299.36,No
4,CUST0004,1,1,0,0,25,1,1,1,0,...,0,1,0,1,Month-to-month,0,Electronic check,52.22,1305.50,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5875,CUST5875,1,0,1,1,71,1,0,1,1,...,0,1,0,0,Month-to-month,1,Mailed check,74.21,5268.91,No
5876,CUST5876,1,0,0,0,22,1,1,1,0,...,1,1,0,1,One year,0,Mailed check,65.43,1439.46,Yes
5877,CUST5877,0,0,0,0,68,0,0,1,1,...,1,1,1,0,One year,1,Bank transfer,59.78,4065.04,No
5878,CUST5878,0,0,1,1,14,0,0,1,1,...,1,1,1,1,Month-to-month,1,Mailed check,91.88,1286.32,No
5879,CUST5879,0,1,1,0,23,1,0,0,0,...,0,0,0,0,Month-to-month,0,Mailed check,25.45,585.35,Yes

In [131]:
data.Churn.replace(['Yes','No'], [1,0], inplace=True)
data.Churn.unique()

C:\Users\User\AppData\Local\Temp\ipykernel_15276\2174583720.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data.Churn.replace(['Yes','No'], [1,0], inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_15276\2174583720.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data.Churn.replace(['Yes','No'], [1,0], inplace=True)

array([0, 1], dtype=int64)

In [132]:
data

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,CUST0000,1,0,0,1,23,0,0,0,0,...,0,0,0,0,Month-to-month,1,Bank transfer,49.85,1146.55,0
1,CUST0001,0,0,1,0,43,0,0,1,1,...,1,0,1,0,Month-to-month,0,Mailed check,100.70,4330.10,1
2,CUST0002,1,1,0,0,51,1,0,1,0,...,1,1,0,0,One year,0,Electronic check,97.33,4963.83,1
3,CUST0003,1,1,0,0,72,1,1,1,1,...,1,0,0,0,Month-to-month,0,Credit card,101.38,7299.36,0
4,CUST0004,1,1,0,0,25,1,1,1,0,...,0,1,0,1,Month-to-month,0,Electronic check,52.22,1305.50,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5875,CUST5875,1,0,1,1,71,1,0,1,1,...,0,1,0,0,Month-to-month,1,Mailed check,74.21,5268.91,0
5876,CUST5876,1,0,0,0,22,1,1,1,0,...,1,1,0,1,One year,0,Mailed check,65.43,1439.46,1
5877,CUST5877,0,0,0,0,68,0,0,1,1,...,1,1,1,0,One year,1,Bank transfer,59.78,4065.04,0
5878,CUST5878,0,0,1,1,14,0,0,1,1,...,1,1,1,1,Month-to-month,1,Mailed check,91.88,1286.32,0
5879,CUST5879,0,1,1,0,23,1,0,0,0,...,0,0,0,0,Month-to-month,0,Mailed check,25.45,585.35,1

In [133]:
data[['PaymentMethod','Contract']]

         PaymentMethod        Contract
0        Bank transfer  Month-to-month
1         Mailed check  Month-to-month
2     Electronic check        One year
3          Credit card  Month-to-month
4     Electronic check  Month-to-month
...                ...             ...
5875      Mailed check  Month-to-month
5876      Mailed check        One year
5877     Bank transfer        One year
5878      Mailed check  Month-to-month
5879      Mailed check  Month-to-month

[5880 rows x 2 columns]

In [134]:
encoded_data = pd.get_dummies(data,columns=['PaymentMethod','Contract'], drop_first=False, dtype=int )

In [135]:
encoded_data
encoded_data.drop('customerID', axis=1, inplace=True)

In [136]:
x = encoded_data.drop('Churn', axis=1)
x

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,...,PaperlessBilling,MonthlyCharges,TotalCharges,PaymentMethod_Bank transfer,PaymentMethod_Credit card,PaymentMethod_Electronic check,PaymentMethod_Mailed check,Contract_Month-to-month,Contract_One year,Contract_Two year
0,1,0,0,1,23,0,0,0,0,0,...,1,49.85,1146.55,1,0,0,0,1,0,0
1,0,0,1,0,43,0,0,1,1,0,...,0,100.70,4330.10,0,0,0,1,1,0,0
2,1,1,0,0,51,1,0,1,0,1,...,0,97.33,4963.83,0,0,1,0,0,1,0
3,1,1,0,0,72,1,1,1,1,0,...,0,101.38,7299.36,0,1,0,0,1,0,0
4,1,1,0,0,25,1,1,1,0,0,...,0,52.22,1305.50,0,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5875,1,0,1,1,71,1,0,1,1,0,...,1,74.21,5268.91,0,0,0,1,1,0,0
5876,1,0,0,0,22,1,1,1,0,0,...,0,65.43,1439.46,0,0,0,1,0,1,0
5877,0,0,0,0,68,0,0,1,1,0,...,1,59.78,4065.04,1,0,0,0,0,1,0
5878,0,0,1,1,14,0,0,1,1,1,...,1,91.88,1286.32,0,0,0,1,1,0,0
5879,0,1,1,0,23,1,0,0,0,0,...,0,25.45,585.35,0,0,0,1,1,0,0

In [137]:
x

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,...,PaperlessBilling,MonthlyCharges,TotalCharges,PaymentMethod_Bank transfer,PaymentMethod_Credit card,PaymentMethod_Electronic check,PaymentMethod_Mailed check,Contract_Month-to-month,Contract_One year,Contract_Two year
0,1,0,0,1,23,0,0,0,0,0,...,1,49.85,1146.55,1,0,0,0,1,0,0
1,0,0,1,0,43,0,0,1,1,0,...,0,100.70,4330.10,0,0,0,1,1,0,0
2,1,1,0,0,51,1,0,1,0,1,...,0,97.33,4963.83,0,0,1,0,0,1,0
3,1,1,0,0,72,1,1,1,1,0,...,0,101.38,7299.36,0,1,0,0,1,0,0
4,1,1,0,0,25,1,1,1,0,0,...,0,52.22,1305.50,0,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5875,1,0,1,1,71,1,0,1,1,0,...,1,74.21,5268.91,0,0,0,1,1,0,0
5876,1,0,0,0,22,1,1,1,0,0,...,0,65.43,1439.46,0,0,0,1,0,1,0
5877,0,0,0,0,68,0,0,1,1,0,...,1,59.78,4065.04,1,0,0,0,0,1,0
5878,0,0,1,1,14,0,0,1,1,1,...,1,91.88,1286.32,0,0,0,1,1,0,0
5879,0,1,1,0,23,1,0,0,0,0,...,0,25.45,585.35,0,0,0,1,1,0,0

In [138]:
y = data['Churn']

In [139]:
y

0       0
1       1
2       1
3       0
4       1
       ..
5875    0
5876    1
5877    0
5878    0
5879    1
Name: Churn, Length: 5880, dtype: int64

In [140]:
from sklearn.model_selection import train_test_split

In [141]:
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=123, test_size=0.20)

In [142]:
x_train.shape

(4704, 24)

In [143]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()

In [144]:
encoded_data.drop('customerID', axis=1, inplace= True)
encoded_data

KeyError: "['customerID'] not found in axis"

In [ ]:
lr.fit(x_train,y_train)

In [145]:
lr.fit(x_train,y_train)

C:\Users\User\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [147]:
print(encoded_data.columns)

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'PaperlessBilling', 'MonthlyCharges', 'TotalCharges',
       'Churn', 'PaymentMethod_Bank transfer', 'PaymentMethod_Credit card',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check',
       'Contract_Month-to-month', 'Contract_One year', 'Contract_Two year'],
      dtype='object')

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [154]:
y_pred_train = lr.predict(x_train)

In [156]:
from sklearn.metrics import classification_report
print(classification_report(y_train,y_pred_train))

              precision    recall  f1-score   support

           0       0.52      0.51      0.51      2353
           1       0.52      0.52      0.52      2351

    accuracy                           0.52      4704
   macro avg       0.52      0.52      0.52      4704
weighted avg       0.52      0.52      0.52      4704

In [164]:
y_pred_test = lr.predict(x_test)

In [168]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred_test))

              precision    recall  f1-score   support

           0       0.54      0.46      0.50       629
           1       0.47      0.55      0.51       547

    accuracy                           0.50      1176
   macro avg       0.51      0.51      0.50      1176
weighted avg       0.51      0.50      0.50      1176