# Discretization and Binning
### Qualitative
- Ordinal : ordinals have natural order
- Nominal : Nominals don't have natural order
### Quantitative
 - Continuous
 - Discrete

In [4]:
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
data = pd.read_excel("emp.xlsx")
data

    Serial  Emp_ID Designation  Department  Age  Salary
0        0    1101     Manager    Accounts   50  200000
1        1    1107     Officer          IT   30   80000
2        2    1203     Officer          HR   28      30
3        3    1005     Manager          HR   45  120000
4        4    2123  Office Boy    Accounts   27   45000
5        5    2451  Accountant  Production   34  100000
6        6    1111  Accountant    Accounts   35  110000
7        7    1001     Officer          IT   25   75000
8        8    1234     Manager          IT   23      30
9        9    2156    Engineer  Production   45   89000
10      10    6543     Officer  Production   29  100000
11      11    3214  Accountant     Account   49  123000
12      12    2156    Engineer  Production   45   89000
13      13    1098     Officer          IT   25  100000
14      14    2912     Officer          IT   31   90000
15      15    1222     Officer  Production   25      30
16      16    2156    Engineer  Production   45   89000
17      17    2123  Office Boy    Accounts   27   45000
18      18    1005     Manager          HR   45  120000
19      19    2123  Office Boy    Accounts   27   45000
20      20    6543     Officer  Production   29  100000
21      21    3214  Accountant     Account   49  123000
22      22    2156    Engineer  Production   45   89000
23      23    1098     Officer          IT   25  100000
24      24    2156    Engineer  Production   45   89000
25      25    2123  Office Boy    Accounts   27   45000

In [ ]:
data.Age

0     50
1     30
2     28
3     45
4     27
5     34
6     35
7     25
8     23
9     45
10    29
11    49
12    45
13    25
14    31
15    25
16    45
17    27
18    45
19    27
20    29
21    49
22    45
23    25
24    45
25    27
Name: Age, dtype: int64

In [ ]:
data.Age.min()

23

In [ ]:
data.Age.max()

50

In [ ]:
data.Age.mean()

np.float64(35.0)

In [ ]:
data.Age.var()

91.2

In [ ]:
data.Age.std()

9.549869109050658

In [ ]:
data['Age_Group'] = pd.cut(data.Age, bins=[20,30,40,50], labels=['Young', 'Adult' ,'Middle'])
data.Age_Group

0     Middle
1      Young
2      Young
3     Middle
4      Young
5      Adult
6      Adult
7      Young
8      Young
9     Middle
10     Young
11    Middle
12    Middle
13     Young
14     Adult
15     Young
16    Middle
17     Young
18    Middle
19     Young
20     Young
21    Middle
22    Middle
23     Young
24    Middle
25     Young
Name: Age_Group, dtype: category
Categories (3, object): ['Young' < 'Adult' < 'Middle']

In [ ]:
data.Age_Group.value_counts()

Age_Group
Young     13
Middle    10
Adult      3
Name: count, dtype: int64

In [ ]:
data[data.Designation=="Accountant"]

    Serial  Emp_ID Designation  Department  Age  Salary Age_Group
5        5    2451  Accountant  Production   34  100000     Adult
6        6    1111  Accountant    Accounts   35  110000     Adult
11      11    3214  Accountant     Account   49  123000    Middle
21      21    3214  Accountant     Account   49  123000    Middle

# Computing Indicator/Dummy Variables/Data Encoding

In [ ]:
for a in "python":
  print (ord(a),end=',')
  print (bin(ord(a)))

112,0b1110000
121,0b1111001
116,0b1110100
104,0b1101000
111,0b1101111
110,0b1101110

In [ ]:
data.Designation.unique()

array(['Manager', 'Officer', 'Office Boy', 'Accountant', 'Engineer'],
      dtype=object)

In [ ]:
# we should not do this encoding
data.Designation.replace(['Manager', 'Officer', 'Office Boy', 'Accountant', 'Engineer'],[0,1,2,3,4])

/tmp/ipykernel_2893/1781896070.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data.Designation.replace(['Manager', 'Officer', 'Office Boy', 'Accountant', 'Engineer'],[0,1,2,3,4])

0     0
1     1
2     1
3     0
4     2
5     3
6     3
7     1
8     0
9     4
10    1
11    3
12    4
13    1
14    1
15    1
16    4
17    2
18    0
19    2
20    1
21    3
22    4
23    1
24    4
25    2
Name: Designation, dtype: int64

In [ ]:
pd.get_dummies(data.Designation, dtype=int)

    Accountant  Engineer  Manager  Office Boy  Officer
0            0         0        1           0        0
1            0         0        0           0        1
2            0         0        0           0        1
3            0         0        1           0        0
4            0         0        0           1        0
5            1         0        0           0        0
6            1         0        0           0        0
7            0         0        0           0        1
8            0         0        1           0        0
9            0         1        0           0        0
10           0         0        0           0        1
11           1         0        0           0        0
12           0         1        0           0        0
13           0         0        0           0        1
14           0         0        0           0        1
15           0         0        0           0        1
16           0         1        0           0        0
17           0         0        0           1        0
18           0         0        1           0        0
19           0         0        0           1        0
20           0         0        0           0        1
21           1         0        0           0        0
22           0         1        0           0        0
23           0         0        0           0        1
24           0         1        0           0        0
25           0         0        0           1        0

In [ ]:
pd.get_dummies(data.Department, dtype=int)

    Account  Accounts  HR  IT  Production
0         0         1   0   0           0
1         0         0   0   1           0
2         0         0   1   0           0
3         0         0   1   0           0
4         0         1   0   0           0
5         0         0   0   0           1
6         0         1   0   0           0
7         0         0   0   1           0
8         0         0   0   1           0
9         0         0   0   0           1
10        0         0   0   0           1
11        1         0   0   0           0
12        0         0   0   0           1
13        0         0   0   1           0
14        0         0   0   1           0
15        0         0   0   0           1
16        0         0   0   0           1
17        0         1   0   0           0
18        0         0   1   0           0
19        0         1   0   0           0
20        0         0   0   0           1
21        1         0   0   0           0
22        0         0   0   0           1
23        0         0   0   1           0
24        0         0   0   0           1
25        0         1   0   0           0

# Data wrangling: Join, Combine and Reshape

## Combining and merging data sets

In [1]:
from google.colab import files
uploaded = files.upload()

Saving test_data.xlsx to test_data.xlsx

In [5]:
data0 = pd.read_excel('test_data.xlsx', sheet_name=0)
data1 = pd.read_excel('test_data.xlsx', sheet_name=1)
data2 = pd.read_excel('test_data.xlsx', sheet_name=2)

In [6]:
data0

   sales_man_id sales_man_name sales_man_city  product_id manager
0             1           Asad        Karachi         123   Jawed
1             2         Sumair         Lahore         123   Jawed
2             3         Farjad        Karachi         145   Najam
3             4         Hassan         Lahore         567   Najam
4             5          Nasir      Hyderabad         234   Jawed
5             6         Kashif      Hyderabad         234  Faisal
6             7           Sana         Lahore         567  Faisal
7             8         Fatima        Karachi         345   Najam
8             9       Abdullah        Karachi         123  Faisal

In [7]:
data1

    sales_man_id sales_man_name sales_man_city  product_id manager  Experience
0              1          Ahmed        Karachi         123   Jawed           2
1             22           Umer         Lahore         123   Jawed           3
2             33        Huzaifa        Karachi         145   Najam           4
3              4         Hassan         Lahore         567   Najam           5
4             55        Hussain      Hyderabad         234   Jawed           6
5             66            Ali      Hyderabad         234  Faisal           7
6             77          Sadaf         Lahore         567  Faisal           8
7             88          Kiran        Karachi         345   Najam           9
8             99            Ali        Karachi         123  Faisal           1
9            101           Asad      Hyderabad         432   Jawed           4
10           101           Asad      Hyderabad         432   Jawed           5

In [8]:
data2

   sales_man_id sales_man_name Region   Sales  Amount
0             2         Sumair       A    100   100000
1             5          Nasir       B    300   450000
2             7           Sana       C    234   125000
3            23           Sana       D    231   652000
4            45         Fatima       E    324   145000
5             1           Asad       F    123   825000
6             9       Abdullah       G    129   125000
7            56          Almas       H    345   325600
8             4         Hassan       I    400   895200

In [9]:
pd.concat([data0,data1],ignore_index=True)

    sales_man_id sales_man_name sales_man_city  product_id manager  Experience
0              1           Asad        Karachi         123   Jawed         NaN
1              2         Sumair         Lahore         123   Jawed         NaN
2              3         Farjad        Karachi         145   Najam         NaN
3              4         Hassan         Lahore         567   Najam         NaN
4              5          Nasir      Hyderabad         234   Jawed         NaN
5              6         Kashif      Hyderabad         234  Faisal         NaN
6              7           Sana         Lahore         567  Faisal         NaN
7              8         Fatima        Karachi         345   Najam         NaN
8              9       Abdullah        Karachi         123  Faisal         NaN
9              1          Ahmed        Karachi         123   Jawed         2.0
10            22           Umer         Lahore         123   Jawed         3.0
11            33        Huzaifa        Karachi         145   Najam         4.0
12             4         Hassan         Lahore         567   Najam         5.0
13            55        Hussain      Hyderabad         234   Jawed         6.0
14            66            Ali      Hyderabad         234  Faisal         7.0
15            77          Sadaf         Lahore         567  Faisal         8.0
16            88          Kiran        Karachi         345   Najam         9.0
17            99            Ali        Karachi         123  Faisal         1.0
18           101           Asad      Hyderabad         432   Jawed         4.0
19           101           Asad      Hyderabad         432   Jawed         5.0

## Merging: Joins

### Explanation of `pd.merge(how=...)`

The `how` parameter in `pd.merge()` dictates which rows are kept from the left and right DataFrames based on the common key(s):

- **`how='inner'` (default)**: Produces only the set of records that match in both DataFrames. It returns a DataFrame containing all rows from `data0` and `data2` that have matching `sales_man_id` values. Rows that do not have a match in both DataFrames are discarded.

- **`how='outer'`**: Produces the set of all records in both DataFrames, matching rows where possible, and filling in `NaN` (Not a Number) for unmatched fields. This means it includes all rows from `data0` and all rows from `data2`, and where there's no match for `sales_man_id`, the columns from the non-matching DataFrame will have `NaN` values.

- **`how='left'`**: Produces all records from the left DataFrame (`data0`) and any matching records from the right DataFrame (`data2`). If there is no match in `data2` for a row in `data0`, the columns from `data2` will be filled with `NaN`.

- **`how='right'`**: Produces all records from the right DataFrame (`data2`) and any matching records from the left DataFrame (`data0`). If there is no match in `data0` for a row in `data2`, the columns from `data0` will be filled with `NaN`.

In [10]:
pd.merge(data0,data2,how='inner',on='sales_man_id')

,sales_man_id,sales_man_name_x,sales_man_city,product_id,manager,sales_man_name_y,Region,Sales,Amount
0,1,Asad,Karachi,123,Jawed,Asad,F,123,825000
1,2,Sumair,Lahore,123,Jawed,Sumair,A,100,100000
2,4,Hassan,Lahore,567,Najam,Hassan,I,400,895200
3,5,Nasir,Hyderabad,234,Jawed,Nasir,B,300,450000
4,7,Sana,Lahore,567,Faisal,Sana,C,234,125000
5,9,Abdullah,Karachi,123,Faisal,Abdullah,G,129,125000

In [12]:
pd.merge(data0,data2, how='outer', on='sales_man_id')

,sales_man_id,sales_man_name_x,sales_man_city,product_id,manager,sales_man_name_y,Region,Sales,Amount
0,1,Asad,Karachi,123.0,Jawed,Asad,F,123.0,825000.0
1,2,Sumair,Lahore,123.0,Jawed,Sumair,A,100.0,100000.0
2,3,Farjad,Karachi,145.0,Najam,NaN,NaN,NaN,NaN
3,4,Hassan,Lahore,567.0,Najam,Hassan,I,400.0,895200.0
4,5,Nasir,Hyderabad,234.0,Jawed,Nasir,B,300.0,450000.0
5,6,Kashif,Hyderabad,234.0,Faisal,NaN,NaN,NaN,NaN
6,7,Sana,Lahore,567.0,Faisal,Sana,C,234.0,125000.0
7,8,Fatima,Karachi,345.0,Najam,NaN,NaN,NaN,NaN
8,9,Abdullah,Karachi,123.0,Faisal,Abdullah,G,129.0,125000.0
9,23,NaN,NaN,NaN,NaN,Sana,D,231.0,652000.0
10,45,NaN,NaN,NaN,NaN,Fatima,E,324.0,145000.0
11,56,NaN,NaN,NaN,NaN,Almas,H,345.0,325600.0

In [13]:
pd.merge(data0,data2, how='left', on='sales_man_id')

,sales_man_id,sales_man_name_x,sales_man_city,product_id,manager,sales_man_name_y,Region,Sales,Amount
0,1,Asad,Karachi,123,Jawed,Asad,F,123.0,825000.0
1,2,Sumair,Lahore,123,Jawed,Sumair,A,100.0,100000.0
2,3,Farjad,Karachi,145,Najam,NaN,NaN,NaN,NaN
3,4,Hassan,Lahore,567,Najam,Hassan,I,400.0,895200.0
4,5,Nasir,Hyderabad,234,Jawed,Nasir,B,300.0,450000.0
5,6,Kashif,Hyderabad,234,Faisal,NaN,NaN,NaN,NaN
6,7,Sana,Lahore,567,Faisal,Sana,C,234.0,125000.0
7,8,Fatima,Karachi,345,Najam,NaN,NaN,NaN,NaN
8,9,Abdullah,Karachi,123,Faisal,Abdullah,G,129.0,125000.0

In [14]:
pd.merge(data0,data2, how='right', on='sales_man_id')

,sales_man_id,sales_man_name_x,sales_man_city,product_id,manager,sales_man_name_y,Region,Sales,Amount
0,2,Sumair,Lahore,123.0,Jawed,Sumair,A,100,100000
1,5,Nasir,Hyderabad,234.0,Jawed,Nasir,B,300,450000
2,7,Sana,Lahore,567.0,Faisal,Sana,C,234,125000
3,23,NaN,NaN,NaN,NaN,Sana,D,231,652000
4,45,NaN,NaN,NaN,NaN,Fatima,E,324,145000
5,1,Asad,Karachi,123.0,Jawed,Asad,F,123,825000
6,9,Abdullah,Karachi,123.0,Faisal,Abdullah,G,129,125000
7,56,NaN,NaN,NaN,NaN,Almas,H,345,325600
8,4,Hassan,Lahore,567.0,Najam,Hassan,I,400,895200