#Capital Asset Pricing Model (CAPM)

In [ ]:
import numpy as np
import pandas as pd
import datetime
import yfinance as yf
import pandas_datareader as web
import plotly.express as px

In [ ]:
year = 2

In [ ]:
end = datetime.datetime.today()
end

datetime.datetime(2026, 7, 12, 12, 37, 41, 123443)

In [ ]:
start = datetime.date(datetime.date.today().year - year, datetime.date.today().month, datetime.date.today().day)
start

datetime.date(2024, 7, 12)

In [ ]:
sp500 = web.DataReader(['sp500'], 'fred', start, end)
sp500.head()

              sp500
DATE
2024-07-12  5615.35
2024-07-15  5631.22
2024-07-16  5667.20
2024-07-17  5588.27
2024-07-18  5544.59

In [ ]:
stocks_list = ['TSLA','AAPL','AMZN','GOOGL']

In [ ]:
stocks_df = pd.DataFrame()
for stock in stocks_list:
  data = yf.download(stock, period=f'{year}y')
  stocks_df[stock] = data['Close']
stocks_df.head()

/tmp/ipykernel_785/634967256.py:3: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(stock, period=f'{year}y')
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_785/634967256.py:3: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(stock, period=f'{year}y')
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_785/634967256.py:3: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(stock, period=f'{year}y')
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_785/634967256.py:3: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(stock, period=f'{year}y')
[*********************100%***********************]  1 of 1 completed

                  TSLA        AAPL        AMZN       GOOGL
Date
2024-07-11  241.029999  225.615631  195.050003  184.150101
2024-07-12  248.229996  228.560104  194.490005  183.653900
2024-07-15  252.639999  232.386917  192.720001  185.102737
2024-07-16  256.559998  232.803345  193.020004  182.512711
2024-07-17  248.500000  226.914383  187.929993  179.634872

In [ ]:
stocks_df.reset_index(inplace=True)
stocks_df

          Date        TSLA        AAPL        AMZN       GOOGL
0   2024-07-11  241.029999  225.615631  195.050003  184.150101
1   2024-07-12  248.229996  228.560104  194.490005  183.653900
2   2024-07-15  252.639999  232.386917  192.720001  185.102737
3   2024-07-16  256.559998  232.803345  193.020004  182.512711
4   2024-07-17  248.500000  226.914383  187.929993  179.634872
..         ...         ...         ...         ...         ...
496 2026-07-06  419.769989  312.660004  244.160004  366.459991
497 2026-07-07  402.899994  310.660004  245.979996  367.029999
498 2026-07-08  394.059998  313.390015  243.619995  361.920013
499 2026-07-09  406.549988  316.220001  247.039993  358.890015
500 2026-07-10  407.760010  315.320007  245.339996  357.179993

[501 rows x 5 columns]

In [ ]:
sp500.reset_index(inplace=True)
sp500

          DATE    sp500
0   2024-07-12  5615.35
1   2024-07-15  5631.22
2   2024-07-16  5667.20
3   2024-07-17  5588.27
4   2024-07-18  5544.59
..         ...      ...
516 2026-07-06  7537.43
517 2026-07-07  7503.85
518 2026-07-08  7482.71
519 2026-07-09  7543.64
520 2026-07-10  7575.39

[521 rows x 2 columns]

In [ ]:
#sp500.rename(columns={'DATE':'Date'}, inplace=True)

In [ ]:
#data = pd.merge(stocks_df, sp500,on='Date', how='inner')
data = pd.merge(stocks_df, sp500,left_on='Date', right_on='DATE', how='inner').drop('DATE',axis=1)
data.head()

        Date        TSLA        AAPL        AMZN       GOOGL    sp500
0 2024-07-12  248.229996  228.560104  194.490005  183.653900  5615.35
1 2024-07-15  252.639999  232.386917  192.720001  185.102737  5631.22
2 2024-07-16  256.559998  232.803345  193.020004  182.512711  5667.20
3 2024-07-17  248.500000  226.914383  187.929993  179.634872  5588.27
4 2024-07-18  249.229996  222.254730  183.750000  176.330368  5544.59

In [ ]:
data.set_index('Date',inplace=True)

In [ ]:
data.index

DatetimeIndex(['2024-07-12', '2024-07-15', '2024-07-16', '2024-07-17',
               '2024-07-18', '2024-07-19', '2024-07-22', '2024-07-23',
               '2024-07-24', '2024-07-25',
               ...
               '2026-06-26', '2026-06-29', '2026-06-30', '2026-07-01',
               '2026-07-02', '2026-07-06', '2026-07-07', '2026-07-08',
               '2026-07-09', '2026-07-10'],
              dtype='datetime64[ns]', name='Date', length=500, freq=None)

In [ ]:
#Functions to plot interactive plotly charts
def interactive_plot(df):
  fig = px.line()
  for i in df.columns:
    fig.add_scatter(x=df.index, y=df[i], name=i)
  fig.update_layout(
      width=800,
      margin=dict(l=20, r=20, t=50, b=20),
      legend=dict(x=1, xanchor="right", y=1.02, yanchor="bottom",
                  orientation='h')
  )
  return fig

In [ ]:
interactive_plot(data)

In [ ]:
def normalize_data(df):
  return data.div(data.iloc[0]).mul(100)

In [ ]:
normalized_data = normalize_data(data)
interactive_plot(normalized_data)