#Pandas for data analysis:
 - Series
 - Data Frame

##Series:
 - Data with a single column/feature

In [ ]:
import pandas as pd

In [ ]:
s1 = pd.Series(['Chairs','Tables','Keyboards','Mouse',"Monitor"], name='Furniture')
s1

0       Chairs
1       Tables
2    Keyboards
3        Mouse
4      Monitor
Name: Furniture, dtype: object

In [ ]:
s1.values

array(['Chairs', 'Tables', 'Keyboards', 'Mouse', 'Monitor'], dtype=object)

In [ ]:
s1.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
s1.name

'Furniture'

In [ ]:
s1.dtype

dtype('O')

In [ ]:
#index with string values are called labels
s1 = pd.Series([10,36,12,50,100],index=['Chairs','Tables','Keyboards','Mouse',"Monitor"],name='Furniture')
s1

Chairs        10
Tables        36
Keyboards     12
Mouse         50
Monitor      100
Name: Furniture, dtype: int64

In [ ]:
s1['Monitor']

np.int64(100)

In [ ]:
s1["Tables":"Mouse"]

Tables       36
Keyboards    12
Mouse        50
Name: Furniture, dtype: int64

# Data with multiple columns

In [ ]:
furniture = {'Furniture':['Chairs','Tables','Keyboards','Mouse',"Monitor"],
             "Quantity":[10,36,12,50,100],
             'City':['Karachi','Lahore','Hyderabad','Peshawar','Multan']}




df = pd.DataFrame

In [ ]:
df

   Furniture  Quantity       City
0     Chairs        10    Karachi
1     Tables        36     Lahore
2  Keyboards        12  Hyderabad
3      Mouse        50   Peshawar
4    Monitor       100     Multan

In [ ]:
df1 = pd.read_excel('employee.xlsx')

In [ ]:
df1

    Serial  Emp_ID Designation  Department   Age    Salary
0        0    1101     Manager    Accounts  50.0  200000.0
1        1    1107     Officer          IT  30.0   80000.0
2        2    1203     Officer          HR  28.0       NaN
3        3    1005     Manager          HR  45.0  120000.0
4        4    2123  Office Boy    Accounts  27.0   45000.0
5        5    2451  Accountant         NaN  34.0  100000.0
6        6    1111  Accountant    Accounts   NaN  110000.0
7        7    1001     Officer          IT  25.0   75000.0
8        8    1234     Manager          IT  23.0       NaN
9        9    2156    Engineer  Production  45.0   89000.0
10      10    6543     Officer  Production  29.0  100000.0
11      11    3214  Accountant     Account  49.0  123000.0
12      12    2156    Engineer  Production  45.0   89000.0
13      13    1098     Officer          IT  25.0  100000.0
14      14    2912     Officer          IT  31.0   90000.0
15      15    1222     Officer         NaN  25.0       NaN
16      16    2156    Engineer  Production  45.0   89000.0
17      17    2123  Office Boy    Accounts  27.0   45000.0
18      18    1005     Manager          HR  45.0  120000.0
19      19    2123  Office Boy    Accounts  27.0   45000.0
20      20    6543     Officer  Production  29.0  100000.0
21      21    3214  Accountant     Account  49.0  123000.0
22      22    2156    Engineer  Production  45.0   89000.0
23      23    1098     Officer          IT  25.0  100000.0
24      24    2156    Engineer  Production  45.0   89000.0
25      25    2123  Office Boy    Accounts  27.0   45000.0

In [ ]:
df1['Department']

0       Accounts
1             IT
2             HR
3             HR
4       Accounts
5            NaN
6       Accounts
7             IT
8             IT
9     Production
10    Production
11       Account
12    Production
13            IT
14            IT
15           NaN
16    Production
17      Accounts
18            HR
19      Accounts
20    Production
21       Account
22    Production
23            IT
24    Production
25      Accounts
Name: Department, dtype: object

In [ ]:
df1['Salary']

0     200000.0
1      80000.0
2          NaN
3     120000.0
4      45000.0
5     100000.0
6     110000.0
7      75000.0
8          NaN
9      89000.0
10    100000.0
11    123000.0
12     89000.0
13    100000.0
14     90000.0
15         NaN
16     89000.0
17     45000.0
18    120000.0
19     45000.0
20    100000.0
21    123000.0
22     89000.0
23    100000.0
24     89000.0
25     45000.0
Name: Salary, dtype: float64

In [ ]:
df1[['Emp_ID','Designation','Age']]

    Emp_ID Designation   Age
0     1101     Manager  50.0
1     1107     Officer  30.0
2     1203     Officer  28.0
3     1005     Manager  45.0
4     2123  Office Boy  27.0
5     2451  Accountant  34.0
6     1111  Accountant   NaN
7     1001     Officer  25.0
8     1234     Manager  23.0
9     2156    Engineer  45.0
10    6543     Officer  29.0
11    3214  Accountant  49.0
12    2156    Engineer  45.0
13    1098     Officer  25.0
14    2912     Officer  31.0
15    1222     Officer  25.0
16    2156    Engineer  45.0
17    2123  Office Boy  27.0
18    1005     Manager  45.0
19    2123  Office Boy  27.0
20    6543     Officer  29.0
21    3214  Accountant  49.0
22    2156    Engineer  45.0
23    1098     Officer  25.0
24    2156    Engineer  45.0
25    2123  Office Boy  27.0

In [ ]:
df1.Age

0     50.0
1     30.0
2     28.0
3     45.0
4     27.0
5     34.0
6      NaN
7     25.0
8     23.0
9     45.0
10    29.0
11    49.0
12    45.0
13    25.0
14    31.0
15    25.0
16    45.0
17    27.0
18    45.0
19    27.0
20    29.0
21    49.0
22    45.0
23    25.0
24    45.0
25    27.0
Name: Age, dtype: float64

In [ ]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
df.dtypes

Furniture    object
Quantity      int64
City         object
dtype: object

### Working with columns
- selecting single column (series)
- slecting multiple columns (DataFrame)
- Adding and deleting columns
- Updating columns

In [ ]:
# selecting one column
df1["Designation"]

0        Manager
1        Officer
2        Officer
3        Manager
4     Office Boy
5     Accountant
6     Accountant
7        Officer
8        Manager
9       Engineer
10       Officer
11    Accountant
12      Engineer
13       Officer
14       Officer
15       Officer
16      Engineer
17    Office Boy
18       Manager
19    Office Boy
20       Officer
21    Accountant
22      Engineer
23       Officer
24      Engineer
25    Office Boy
Name: Designation, dtype: object

In [ ]:
df1.Designation

0        Manager
1        Officer
2        Officer
3        Manager
4     Office Boy
5     Accountant
6     Accountant
7        Officer
8        Manager
9       Engineer
10       Officer
11    Accountant
12      Engineer
13       Officer
14       Officer
15       Officer
16      Engineer
17    Office Boy
18       Manager
19    Office Boy
20       Officer
21    Accountant
22      Engineer
23       Officer
24      Engineer
25    Office Boy
Name: Designation, dtype: object

In [ ]:
# selecting more than one column
df1[['Designation','Salary']]

   Designation    Salary
0      Manager  200000.0
1      Officer   80000.0
2      Officer       NaN
3      Manager  120000.0
4   Office Boy   45000.0
5   Accountant  100000.0
6   Accountant  110000.0
7      Officer   75000.0
8      Manager       NaN
9     Engineer   89000.0
10     Officer  100000.0
11  Accountant  123000.0
12    Engineer   89000.0
13     Officer  100000.0
14     Officer   90000.0
15     Officer       NaN
16    Engineer   89000.0
17  Office Boy   45000.0
18     Manager  120000.0
19  Office Boy   45000.0
20     Officer  100000.0
21  Accountant  123000.0
22    Engineer   89000.0
23     Officer  100000.0
24    Engineer   89000.0
25  Office Boy   45000.0

In [ ]:
df1[["Department",'Salary','Designation']]

    Department    Salary Designation
0     Accounts  200000.0     Manager
1           IT   80000.0     Officer
2           HR       NaN     Officer
3           HR  120000.0     Manager
4     Accounts   45000.0  Office Boy
5          NaN  100000.0  Accountant
6     Accounts  110000.0  Accountant
7           IT   75000.0     Officer
8           IT       NaN     Manager
9   Production   89000.0    Engineer
10  Production  100000.0     Officer
11     Account  123000.0  Accountant
12  Production   89000.0    Engineer
13          IT  100000.0     Officer
14          IT   90000.0     Officer
15         NaN       NaN     Officer
16  Production   89000.0    Engineer
17    Accounts   45000.0  Office Boy
18          HR  120000.0     Manager
19    Accounts   45000.0  Office Boy
20  Production  100000.0     Officer
21     Account  123000.0  Accountant
22  Production   89000.0    Engineer
23          IT  100000.0     Officer
24  Production   89000.0    Engineer
25    Accounts   45000.0  Office Boy

In [ ]:
df1.values

array([[0, 1101, 'Manager', 'Accounts', 50.0, 200000.0],
       [1, 1107, 'Officer', 'IT', 30.0, 80000.0],
       [2, 1203, 'Officer', 'HR', 28.0, nan],
       [3, 1005, 'Manager', 'HR', 45.0, 120000.0],
       [4, 2123, 'Office Boy', 'Accounts', 27.0, 45000.0],
       [5, 2451, 'Accountant', nan, 34.0, 100000.0],
       [6, 1111, 'Accountant', 'Accounts', nan, 110000.0],
       [7, 1001, 'Officer', 'IT', 25.0, 75000.0],
       [8, 1234, 'Manager', 'IT', 23.0, nan],
       [9, 2156, 'Engineer', 'Production', 45.0, 89000.0],
       [10, 6543, 'Officer', 'Production', 29.0, 100000.0],
       [11, 3214, 'Accountant', 'Account', 49.0, 123000.0],
       [12, 2156, 'Engineer', 'Production', 45.0, 89000.0],
       [13, 1098, 'Officer', 'IT', 25.0, 100000.0],
       [14, 2912, 'Officer', 'IT', 31.0, 90000.0],
       [15, 1222, 'Officer', nan, 25.0, nan],
       [16, 2156, 'Engineer', 'Production', 45.0, 89000.0],
       [17, 2123, 'Office Boy', 'Accounts', 27.0, 45000.0],
       [18, 1005, 'Manager', 'HR', 45.0, 120000.0],
       [19, 2123, 'Office Boy', 'Accounts', 27.0, 45000.0],
       [20, 6543, 'Officer', 'Production', 29.0, 100000.0],
       [21, 3214, 'Accountant', 'Account', 49.0, 123000.0],
       [22, 2156, 'Engineer', 'Production', 45.0, 89000.0],
       [23, 1098, 'Officer', 'IT', 25.0, 100000.0],
       [24, 2156, 'Engineer', 'Production', 45.0, 89000.0],
       [25, 2123, 'Office Boy', 'Accounts', 27.0, 45000.0]], dtype=object)

In [ ]:
df1

    Serial  Emp_ID Designation  Department   Age    Salary
0        0    1101     Manager    Accounts  50.0  200000.0
1        1    1107     Officer          IT  30.0   80000.0
2        2    1203     Officer          HR  28.0       NaN
3        3    1005     Manager          HR  45.0  120000.0
4        4    2123  Office Boy    Accounts  27.0   45000.0
5        5    2451  Accountant         NaN  34.0  100000.0
6        6    1111  Accountant    Accounts   NaN  110000.0
7        7    1001     Officer          IT  25.0   75000.0
8        8    1234     Manager          IT  23.0       NaN
9        9    2156    Engineer  Production  45.0   89000.0
10      10    6543     Officer  Production  29.0  100000.0
11      11    3214  Accountant     Account  49.0  123000.0
12      12    2156    Engineer  Production  45.0   89000.0
13      13    1098     Officer          IT  25.0  100000.0
14      14    2912     Officer          IT  31.0   90000.0
15      15    1222     Officer         NaN  25.0       NaN
16      16    2156    Engineer  Production  45.0   89000.0
17      17    2123  Office Boy    Accounts  27.0   45000.0
18      18    1005     Manager          HR  45.0  120000.0
19      19    2123  Office Boy    Accounts  27.0   45000.0
20      20    6543     Officer  Production  29.0  100000.0
21      21    3214  Accountant     Account  49.0  123000.0
22      22    2156    Engineer  Production  45.0   89000.0
23      23    1098     Officer          IT  25.0  100000.0
24      24    2156    Engineer  Production  45.0   89000.0
25      25    2123  Office Boy    Accounts  27.0   45000.0

In [ ]:
df1["Tax"]=1000

In [ ]:
df1

    Serial  Emp_ID Designation  Department   Age    Salary   Tax
0        0    1101     Manager    Accounts  50.0  200000.0  1000
1        1    1107     Officer          IT  30.0   80000.0  1000
2        2    1203     Officer          HR  28.0       NaN  1000
3        3    1005     Manager          HR  45.0  120000.0  1000
4        4    2123  Office Boy    Accounts  27.0   45000.0  1000
5        5    2451  Accountant         NaN  34.0  100000.0  1000
6        6    1111  Accountant    Accounts   NaN  110000.0  1000
7        7    1001     Officer          IT  25.0   75000.0  1000
8        8    1234     Manager          IT  23.0       NaN  1000
9        9    2156    Engineer  Production  45.0   89000.0  1000
10      10    6543     Officer  Production  29.0  100000.0  1000
11      11    3214  Accountant     Account  49.0  123000.0  1000
12      12    2156    Engineer  Production  45.0   89000.0  1000
13      13    1098     Officer          IT  25.0  100000.0  1000
14      14    2912     Officer          IT  31.0   90000.0  1000
15      15    1222     Officer         NaN  25.0       NaN  1000
16      16    2156    Engineer  Production  45.0   89000.0  1000
17      17    2123  Office Boy    Accounts  27.0   45000.0  1000
18      18    1005     Manager          HR  45.0  120000.0  1000
19      19    2123  Office Boy    Accounts  27.0   45000.0  1000
20      20    6543     Officer  Production  29.0  100000.0  1000
21      21    3214  Accountant     Account  49.0  123000.0  1000
22      22    2156    Engineer  Production  45.0   89000.0  1000
23      23    1098     Officer          IT  25.0  100000.0  1000
24      24    2156    Engineer  Production  45.0   89000.0  1000
25      25    2123  Office Boy    Accounts  27.0   45000.0  1000

In [ ]:
df1["Tax"] = df1.Salary*.10
df1

    Serial  Emp_ID Designation  Department   Age    Salary      Tax
0        0    1101     Manager    Accounts  50.0  200000.0  20000.0
1        1    1107     Officer          IT  30.0   80000.0   8000.0
2        2    1203     Officer          HR  28.0       NaN      NaN
3        3    1005     Manager          HR  45.0  120000.0  12000.0
4        4    2123  Office Boy    Accounts  27.0   45000.0   4500.0
5        5    2451  Accountant         NaN  34.0  100000.0  10000.0
6        6    1111  Accountant    Accounts   NaN  110000.0  11000.0
7        7    1001     Officer          IT  25.0   75000.0   7500.0
8        8    1234     Manager          IT  23.0       NaN      NaN
9        9    2156    Engineer  Production  45.0   89000.0   8900.0
10      10    6543     Officer  Production  29.0  100000.0  10000.0
11      11    3214  Accountant     Account  49.0  123000.0  12300.0
12      12    2156    Engineer  Production  45.0   89000.0   8900.0
13      13    1098     Officer          IT  25.0  100000.0  10000.0
14      14    2912     Officer          IT  31.0   90000.0   9000.0
15      15    1222     Officer         NaN  25.0       NaN      NaN
16      16    2156    Engineer  Production  45.0   89000.0   8900.0
17      17    2123  Office Boy    Accounts  27.0   45000.0   4500.0
18      18    1005     Manager          HR  45.0  120000.0  12000.0
19      19    2123  Office Boy    Accounts  27.0   45000.0   4500.0
20      20    6543     Officer  Production  29.0  100000.0  10000.0
21      21    3214  Accountant     Account  49.0  123000.0  12300.0
22      22    2156    Engineer  Production  45.0   89000.0   8900.0
23      23    1098     Officer          IT  25.0  100000.0  10000.0
24      24    2156    Engineer  Production  45.0   89000.0   8900.0
25      25    2123  Office Boy    Accounts  27.0   45000.0   4500.0

In [ ]:
def calc_tax(salary):
  if salary >= 200000:
    return salary*.20
  elif salary >= 100000:
    return salary*.10
  elif salary >= 75000:
    return salary*.075
  elif salary >= 50000:
    return salary*.05
  else:
    return salary*.010

In [ ]:
# using function
df1["Tax"] = df1.Salary.apply(calc_tax)
df1

    Serial  Emp_ID Designation  Department   Age    Salary      Tax
0        0    1101     Manager    Accounts  50.0  200000.0  40000.0
1        1    1107     Officer          IT  30.0   80000.0   6000.0
2        2    1203     Officer          HR  28.0       NaN      NaN
3        3    1005     Manager          HR  45.0  120000.0  12000.0
4        4    2123  Office Boy    Accounts  27.0   45000.0    450.0
5        5    2451  Accountant         NaN  34.0  100000.0  10000.0
6        6    1111  Accountant    Accounts   NaN  110000.0  11000.0
7        7    1001     Officer          IT  25.0   75000.0   5625.0
8        8    1234     Manager          IT  23.0       NaN      NaN
9        9    2156    Engineer  Production  45.0   89000.0   6675.0
10      10    6543     Officer  Production  29.0  100000.0  10000.0
11      11    3214  Accountant     Account  49.0  123000.0  12300.0
12      12    2156    Engineer  Production  45.0   89000.0   6675.0
13      13    1098     Officer          IT  25.0  100000.0  10000.0
14      14    2912     Officer          IT  31.0   90000.0   6750.0
15      15    1222     Officer         NaN  25.0       NaN      NaN
16      16    2156    Engineer  Production  45.0   89000.0   6675.0
17      17    2123  Office Boy    Accounts  27.0   45000.0    450.0
18      18    1005     Manager          HR  45.0  120000.0  12000.0
19      19    2123  Office Boy    Accounts  27.0   45000.0    450.0
20      20    6543     Officer  Production  29.0  100000.0  10000.0
21      21    3214  Accountant     Account  49.0  123000.0  12300.0
22      22    2156    Engineer  Production  45.0   89000.0   6675.0
23      23    1098     Officer          IT  25.0  100000.0  10000.0
24      24    2156    Engineer  Production  45.0   89000.0   6675.0
25      25    2123  Office Boy    Accounts  27.0   45000.0    450.0

In [ ]:
#using lambda
df1["Tax"] = df1.Salary.apply(lambda sal:
                              sal*0.20 if sal>=200000
                              else sal*.15 if sal>=150000
                              else sal*.10 if sal>= 100000
                              else sal*.075 if sal>=75000
                              else sal*.05 if sal>=50000
                              else sal*.010)
df1

    Serial  Emp_ID Designation  Department   Age    Salary      Tax
0        0    1101     Manager    Accounts  50.0  200000.0  40000.0
1        1    1107     Officer          IT  30.0   80000.0   6000.0
2        2    1203     Officer          HR  28.0       NaN      NaN
3        3    1005     Manager          HR  45.0  120000.0  12000.0
4        4    2123  Office Boy    Accounts  27.0   45000.0    450.0
5        5    2451  Accountant         NaN  34.0  100000.0  10000.0
6        6    1111  Accountant    Accounts   NaN  110000.0  11000.0
7        7    1001     Officer          IT  25.0   75000.0   5625.0
8        8    1234     Manager          IT  23.0       NaN      NaN
9        9    2156    Engineer  Production  45.0   89000.0   6675.0
10      10    6543     Officer  Production  29.0  100000.0  10000.0
11      11    3214  Accountant     Account  49.0  123000.0  12300.0
12      12    2156    Engineer  Production  45.0   89000.0   6675.0
13      13    1098     Officer          IT  25.0  100000.0  10000.0
14      14    2912     Officer          IT  31.0   90000.0   6750.0
15      15    1222     Officer         NaN  25.0       NaN      NaN
16      16    2156    Engineer  Production  45.0   89000.0   6675.0
17      17    2123  Office Boy    Accounts  27.0   45000.0    450.0
18      18    1005     Manager          HR  45.0  120000.0  12000.0
19      19    2123  Office Boy    Accounts  27.0   45000.0    450.0
20      20    6543     Officer  Production  29.0  100000.0  10000.0
21      21    3214  Accountant     Account  49.0  123000.0  12300.0
22      22    2156    Engineer  Production  45.0   89000.0   6675.0
23      23    1098     Officer          IT  25.0  100000.0  10000.0
24      24    2156    Engineer  Production  45.0   89000.0   6675.0
25      25    2123  Office Boy    Accounts  27.0   45000.0    450.0

##Querry Filters

In [52]:
# need the data of all managers
df1[df1.Designation=='Manager']

    Serial  Emp_ID Designation Department   Age    Salary      Tax
0        0    1101     Manager   Accounts  50.0  200000.0  40000.0
3        3    1005     Manager         HR  45.0  120000.0  12000.0
8        8    1234     Manager         IT  23.0       NaN      NaN
18      18    1005     Manager         HR  45.0  120000.0  12000.0

In [53]:
# need all the employees of IT
df1[df1.Department=='IT']

    Serial  Emp_ID Designation Department   Age    Salary      Tax
1        1    1107     Officer         IT  30.0   80000.0   6000.0
7        7    1001     Officer         IT  25.0   75000.0   5625.0
8        8    1234     Manager         IT  23.0       NaN      NaN
13      13    1098     Officer         IT  25.0  100000.0  10000.0
14      14    2912     Officer         IT  31.0   90000.0   6750.0
23      23    1098     Officer         IT  25.0  100000.0  10000.0

In [55]:
# all employees ages more than 30
df1[df1.Age>30]

    Serial  Emp_ID Designation  Department   Age    Salary      Tax
0        0    1101     Manager    Accounts  50.0  200000.0  40000.0
3        3    1005     Manager          HR  45.0  120000.0  12000.0
5        5    2451  Accountant         NaN  34.0  100000.0  10000.0
9        9    2156    Engineer  Production  45.0   89000.0   6675.0
11      11    3214  Accountant     Account  49.0  123000.0  12300.0
12      12    2156    Engineer  Production  45.0   89000.0   6675.0
14      14    2912     Officer          IT  31.0   90000.0   6750.0
16      16    2156    Engineer  Production  45.0   89000.0   6675.0
18      18    1005     Manager          HR  45.0  120000.0  12000.0
21      21    3214  Accountant     Account  49.0  123000.0  12300.0
22      22    2156    Engineer  Production  45.0   89000.0   6675.0
24      24    2156    Engineer  Production  45.0   89000.0   6675.0

In [57]:
# Number of employees in every department
df1.Department.value_counts()

Department
Production    7
Accounts      6
IT            6
HR            3
Account       2
Name: count, dtype: int64

In [59]:
df1.Department.replace('Account','Accounts',inplace=True)

/tmp/ipykernel_1168/1628134903.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1.Department.replace('Account','Accounts',inplace=True)

In [60]:
df1.Department.value_counts()

Department
Accounts      8
Production    7
IT            6
HR            3
Name: count, dtype: int64

In [63]:
# what is the total salary of Managers
df1[df1.Designation=='Manager']['Salary'].sum()

np.float64(440000.0)

In [66]:
# what is the average salary of IT employees
df1[df1.Department=='IT']['Salary'].mean()

np.float64(89000.0)

In [67]:
# what is the maximum salary in accounts department
df1[df1.Department=='Accounts']['Salary'].max()

200000.0

In [69]:
# what is the min age of Manager
df1[df1.Designation=='Manager']['Age'].min()

23.0

In [70]:
# what is the average age of employee in HR
df1[df1.Department=='HR']['Age'].mean()

np.float64(39.333333333333336)

In [71]:
# All officers in accounts
df1[(df1.Designation=='Officer') & (df1.Department=='Accounts')]

Empty DataFrame
Columns: [Serial, Emp_ID, Designation, Department, Age, Salary, Tax]
Index: []

In [75]:
# All Managers having salary greater than or equal to 100K
df1[(df1.Designation=='Manager') & (df1.Salary>=10000)]

    Serial  Emp_ID Designation Department   Age    Salary      Tax
0        0    1101     Manager   Accounts  50.0  200000.0  40000.0
3        3    1005     Manager         HR  45.0  120000.0  12000.0
18      18    1005     Manager         HR  45.0  120000.0  12000.0

In [79]:
# all the employees with salalry greater than average salary
df1[df1.Salary>df1.Salary.mean()]

    Serial  Emp_ID Designation  Department   Age    Salary      Tax
0        0    1101     Manager    Accounts  50.0  200000.0  40000.0
3        3    1005     Manager          HR  45.0  120000.0  12000.0
5        5    2451  Accountant         NaN  34.0  100000.0  10000.0
6        6    1111  Accountant    Accounts   NaN  110000.0  11000.0
10      10    6543     Officer  Production  29.0  100000.0  10000.0
11      11    3214  Accountant    Accounts  49.0  123000.0  12300.0
13      13    1098     Officer          IT  25.0  100000.0  10000.0
18      18    1005     Manager          HR  45.0  120000.0  12000.0
20      20    6543     Officer  Production  29.0  100000.0  10000.0
21      21    3214  Accountant    Accounts  49.0  123000.0  12300.0
23      23    1098     Officer          IT  25.0  100000.0  10000.0