#Date and Time Data Types and Tools

In [28]:
from datetime import datetime

In [29]:
today = datetime.now()

In [30]:
today

datetime.datetime(2026, 7, 5, 12, 19, 49, 740768)

In [31]:
today.date()

datetime.date(2026, 7, 5)

In [32]:
today.time()

datetime.time(12, 19, 49, 740768)

In [33]:
today.day

5

In [34]:
today.month

7

In [35]:
today.year

2026

In [36]:
today.second

49

In [37]:
today.hour

12

In [38]:
today.year, today.month, today.day

(2026, 7, 5)

In [39]:
print(today.strftime('%A'))

Sunday

In [41]:
print(today.strftime('%a'))

Sun

In [48]:
delta = datetime(2011, 1, 7) - datetime(2008, 6, 24, 8, 15)

In [49]:
delta.days

926

In [50]:
delta.seconds

56700

In [51]:
from datetime import timedelta

In [52]:
start = datetime(2011, 1, 7)

In [53]:
start + timedelta(12)

datetime.datetime(2011, 1, 19, 0, 0)

In [54]:
start - 2 * timedelta(12)

datetime.datetime(2010, 12, 14, 0, 0)

##Converting Between String and Datetime

In [55]:
dob = datetime(2000, 7, 5)

In [56]:
dob

datetime.datetime(2000, 7, 5, 0, 0)

In [57]:
dob.strftime('%d-%m-%Y')

'05-07-2000'

### String to Date

In [58]:
value = '2011-01-03'
datetime.strptime(value, '%Y-%m-%d')

datetime.datetime(2011, 1, 3, 0, 0)

In [59]:
datestrs = ['7/6/2011', '8/6/2011']

In [61]:
[datetime.strptime(x, '%m/%d/%Y')for x in datestrs]

[datetime.datetime(2011, 7, 6, 0, 0), datetime.datetime(2011, 8, 6, 0, 0)]

##Time Series Basics

In [69]:
import numpy as np
import pandas as pd

In [70]:
dates = [datetime(2011, 1, 2), datetime(2011, 1, 5),
        datetime(2011, 1, 7), datetime(2011, 1, 8),
        datetime(2011, 1, 10), datetime(2011, 1, 12)]

In [71]:
ts = pd.Series(np.random.randn(6), index=dates)

In [72]:
ts

2011-01-02    0.580477
2011-01-05    0.388483
2011-01-07    1.025377
2011-01-08    0.016403
2011-01-10   -0.386968
2011-01-12    1.753895
dtype: float64

In [74]:
longer_ts = pd.Series(np.random.randn(100), index=pd.date_range('1/1/2000', periods=100))
longer_ts

2000-01-01    0.762403
2000-01-02    0.546357
2000-01-03   -0.270071
2000-01-04   -0.132814
2000-01-05   -0.446228
                ...
2000-04-05    0.095850
2000-04-06   -0.344122
2000-04-07    0.181573
2000-04-08    0.027806
2000-04-09   -0.254675
Freq: D, Length: 100, dtype: float64

In [87]:
longer_ts['2000-1-01':'2000-12-31']

2000-01-01    0.762403
2000-01-02    0.546357
2000-01-03   -0.270071
2000-01-04   -0.132814
2000-01-05   -0.446228
                ...
2000-04-05    0.095850
2000-04-06   -0.344122
2000-04-07    0.181573
2000-04-08    0.027806
2000-04-09   -0.254675
Freq: D, Length: 100, dtype: float64