In [2]:
import pandas as pd

In [5]:
data = pd.read_excel("SaleData.xlsx")

In [6]:
data

,S.No.,OrderDate,Region,Manager,SalesMan,Item,Units,Unit_price,Sale_amt
0,1,2019-08-07,Central,Hermann,Shelli,Video Games,42.0,58.5,2457.0
1,2,2019-08-24,West,Timothy,Stephen,Desk,3.0,125.0,375.0
2,3,2019-09-10,Central,Timothy,David,Television,7.0,1198.0,8386.0
3,4,2018-01-06,East,Martha,Alexander,Television,95.0,1198.0,113810.0
4,5,2018-01-23,Central,Hermann,Shelli,Home Theater,50.0,500.0,25000.0
5,6,2018-02-09,Central,Hermann,Luis,Television,36.0,1198.0,43128.0
6,7,2018-02-26,Central,NaN,David,Cell Phone,27.0,225.0,6075.0
7,8,2018-03-15,West,Timothy,Stephen,Television,NaN,1198.0,0.0
8,9,2018-04-01,East,Martha,Alexander,Home Theater,60.0,500.0,30000.0
9,10,2018-04-18,NaN,Martha,Steven,Television,75.0,1198.0,89850.0
10,11,2018-05-05,Central,Hermann,NaN,Television,90.0,1198.0,107820.0
11,12,2018-05-22,West,Douglas,Michael,Television,32.0,1198.0,38336.0
12,13,2018-06-08,East,Martha,Alexander,Home Theater,60.0,500.0,30000.0
13,14,2018-06-25,Central,Hermann,Sigal,Television,90.0,1198.0,107820.0
14,15,2018-07-12,East,Martha,Diana,Home Theater,29.0,500.0,14500.0
15,16,2018-07-29,NaN,Douglas,Karen,Home Theater,81.0,500.0,40500.0
16,17,2018-08-15,East,Martha,Alexander,NaN,35.0,1198.0,41930.0
17,18,2018-09-01,Central,Douglas,John,Desk,2.0,125.0,250.0
18,19,2018-09-18,East,Martha,Alexander,Video Games,16.0,58.5,936.0
19,20,2018-10-05,Central,Hermann,Sigal,Home Theater,28.0,500.0,14000.0
20,21,2018-10-22,East,Martha,Alexander,Cell Phone,64.0,225.0,14400.0
21,22,2018-11-08,East,Douglas,Karen,Cell Phone,15.0,225.0,3375.0
22,23,2018-11-25,Central,Hermann,Shelli,Video Games,96.0,58.5,5616.0
23,24,2018-12-12,Central,Douglas,John,Television,67.0,1198.0,80266.0
24,25,2018-12-29,East,Douglas,Karen,NaN,74.0,58.5,4329.0
25,26,2019-01-15,Central,Timothy,David,Home Theater,46.0,500.0,23000.0
26,27,2019-02-01,Central,Douglas,John,Home Theater,87.0,500.0,43500.0
27,28,2019-02-18,East,Martha,Alexander,Home Theater,4.0,500.0,2000.0
28,29,2019-03-07,West,Timothy,Stephen,Home Theater,7.0,500.0,3500.0
29,30,2019-03-24,Central,Hermann,Luis,Video Games,50.0,58.5,2925.0
30,31,2019-04-10,Central,Martha,Steven,Television,NaN,1198.0,0.0
31,32,2019-04-27,East,Martha,Diana,Cell Phone,96.0,225.0,21600.0
32,33,2019-05-14,Central,Timothy,David,Television,53.0,1198.0,63494.0
33,34,2019-05-31,Central,Timothy,David,Home Theater,80.0,500.0,40000.0
34,35,2019-06-17,Central,Hermann,Shelli,Desk,5.0,125.0,625.0
35,36,2019-07-04,East,Martha,Alexander,Video Games,NaN,58.5,0.0
36,37,2019-07-21,Central,Hermann,Sigal,Video Games,55.0,58.5,3217.5
37,38,2019-08-07,Central,Hermann,NaN,Video Games,42.0,58.5,2457.0
38,39,2019-08-24,West,Timothy,Stephen,Desk,3.0,125.0,375.0
39,40,2019-09-10,Central,Timothy,David,Television,7.0,1198.0,8386.0
40,41,2019-09-27,West,Timothy,Stephen,Cell Phone,76.0,225.0,17100.0
41,42,2019-10-14,West,Douglas,Michael,Home Theater,57.0,500.0,28500.0
42,43,2019-10-31,Central,Martha,Steven,Television,14.0,1198.0,16772.0
43,44,2019-11-17,Central,Hermann,Luis,Home Theater,11.0,500.0,5500.0
44,45,2019-12-04,Central,Hermann,Luis,Home Theater,94.0,500.0,47000.0
45,46,2019-12-21,Central,Martha,Steven,Home Theater,28.0,500.0,14000.0
46,47,2019-04-27,East,Martha,Diana,Cell Phone,96.0,225.0,21600.0
47,48,2019-02-01,Central,Douglas,John,Home Theater,87.0,500.0,43500.0
48,49,2019-03-24,Central,Hermann,Luis,Video Games,50.0,58.5,2925.0
49,50,2019-04-10,Central,Martha,Steven,Television,66.0,1198.0,79068.0
50,51,2019-04-27,East,Martha,Diana,Cell Phone,96.0,225.0,21600.0
51,52,2019-05-14,Central,Timothy,David,Television,53.0,1198.0,63494.0

In [10]:
# check how many different regions we have in data
data.Region.unique()

array(['Central', 'West', 'East', nan], dtype=object)

In [11]:
data.Manager.unique()

array(['Hermann', 'Timothy', 'Martha', nan, 'Douglas'], dtype=object)

In [23]:
data.Item.unique()

array(['Video Games', 'Desk', 'Television', 'Home Theater', 'Cell Phone',
       nan], dtype=object)

In [25]:
data.SalesMan.unique()

array(['Shelli', 'Stephen', 'David', 'Alexander', 'Luis', 'Steven', nan,
       'Michael', 'Sigal', 'Diana', 'Karen', 'John'], dtype=object)

In [12]:
data[data.Region=='Central']

,S.No.,OrderDate,Region,Manager,SalesMan,Item,Units,Unit_price,Sale_amt
0,1,2019-08-07,Central,Hermann,Shelli,Video Games,42.0,58.5,2457.0
2,3,2019-09-10,Central,Timothy,David,Television,7.0,1198.0,8386.0
4,5,2018-01-23,Central,Hermann,Shelli,Home Theater,50.0,500.0,25000.0
5,6,2018-02-09,Central,Hermann,Luis,Television,36.0,1198.0,43128.0
6,7,2018-02-26,Central,NaN,David,Cell Phone,27.0,225.0,6075.0
10,11,2018-05-05,Central,Hermann,NaN,Television,90.0,1198.0,107820.0
13,14,2018-06-25,Central,Hermann,Sigal,Television,90.0,1198.0,107820.0
17,18,2018-09-01,Central,Douglas,John,Desk,2.0,125.0,250.0
19,20,2018-10-05,Central,Hermann,Sigal,Home Theater,28.0,500.0,14000.0
22,23,2018-11-25,Central,Hermann,Shelli,Video Games,96.0,58.5,5616.0
23,24,2018-12-12,Central,Douglas,John,Television,67.0,1198.0,80266.0
25,26,2019-01-15,Central,Timothy,David,Home Theater,46.0,500.0,23000.0
26,27,2019-02-01,Central,Douglas,John,Home Theater,87.0,500.0,43500.0
29,30,2019-03-24,Central,Hermann,Luis,Video Games,50.0,58.5,2925.0
30,31,2019-04-10,Central,Martha,Steven,Television,NaN,1198.0,0.0
32,33,2019-05-14,Central,Timothy,David,Television,53.0,1198.0,63494.0
33,34,2019-05-31,Central,Timothy,David,Home Theater,80.0,500.0,40000.0
34,35,2019-06-17,Central,Hermann,Shelli,Desk,5.0,125.0,625.0
36,37,2019-07-21,Central,Hermann,Sigal,Video Games,55.0,58.5,3217.5
37,38,2019-08-07,Central,Hermann,NaN,Video Games,42.0,58.5,2457.0
39,40,2019-09-10,Central,Timothy,David,Television,7.0,1198.0,8386.0
42,43,2019-10-31,Central,Martha,Steven,Television,14.0,1198.0,16772.0
43,44,2019-11-17,Central,Hermann,Luis,Home Theater,11.0,500.0,5500.0
44,45,2019-12-04,Central,Hermann,Luis,Home Theater,94.0,500.0,47000.0
45,46,2019-12-21,Central,Martha,Steven,Home Theater,28.0,500.0,14000.0
47,48,2019-02-01,Central,Douglas,John,Home Theater,87.0,500.0,43500.0
48,49,2019-03-24,Central,Hermann,Luis,Video Games,50.0,58.5,2925.0
49,50,2019-04-10,Central,Martha,Steven,Television,66.0,1198.0,79068.0
51,52,2019-05-14,Central,Timothy,David,Television,53.0,1198.0,63494.0

In [22]:
# total sales from west
data[data.Region=='West']['Sale_amt'].sum()

np.float64(88186.0)

In [20]:
# total Television sales in East
data[(data.Region=='East') & (data.Item=='Television')]

,S.No.,OrderDate,Region,Manager,SalesMan,Item,Units,Unit_price,Sale_amt
3,4,2018-01-06,East,Martha,Alexander,Television,95.0,1198.0,113810.0

In [28]:
# number of cellphones sold by Alexander in Central
data[(data.Region=='Central') & (data.SalesMan=='Alexander') & (data.Item=='Cell Phone')]

Empty DataFrame
Columns: [S.No., OrderDate, Region, Manager, SalesMan, Item, Units, Unit_price, Sale_amt]
Index: []

In [29]:
# number of cellphones sold by David in Central
data[(data.Region=='Central') & (data.SalesMan=='David') & (data.Item=='Cell Phone')]

,S.No.,OrderDate,Region,Manager,SalesMan,Item,Units,Unit_price,Sale_amt
6,7,2018-02-26,Central,NaN,David,Cell Phone,27.0,225.0,6075.0

In [51]:
# John and Diana total sales of videogames in central region
data[((data.SalesMan=='John') | (data.SalesMan=='Diana')) & (data.Item=='Video Games') & (data.Region=='Central')]['Sale_amt'].sum()

np.float64(0.0)

In [55]:
# every region total sale
data[data.Region=='Central']['Sale_amt'].sum()

np.float64(860681.5)

In [56]:
data[data.Region=='East']['Sale_amt'].sum()

np.float64(320080.0)

In [57]:
data[data.Region=='West']['Sale_amt'].sum()

np.float64(88186.0)

In [62]:
df = pd.read_excel('gby.xlsx')

In [63]:
df

   ids     Name  Age Designation  Grade  Dept  Salary
0    1    Nasir   23     Officer      15  Acc   123000
1    2      Ali   34       Clerk      16  Fin   200000
2    3   Faisal   23     Officer      17   IT   200000
3    4    Imran   45       Clerk      18   IT   230000
4    5   Kashif   54     Manager      18  Acc   231000
5    6    Saima   43     Manager      18  Fin   300000
6    7    Aqsa    32  Supervisor      17   IT   234000
7    8    Zoya    23     Manager      17   IT   250000
8    9    Salma   22     Manager      17  Fin   231000
9   10   Faheem   56     Officer      16   IT   100000

In [66]:
df.groupby('Designation')['Salary '].sum()

Designation
Clerk          430000
Manager       1012000
Officer        423000
Supervisor     234000
Name: Salary , dtype: int64

In [67]:
df.columns=['ids','Name','Age','Designation','Grade','Dept','Salary']

In [69]:
df.groupby('Designation')['Salary'].sum()

Designation
Clerk          430000
Manager       1012000
Officer        423000
Supervisor     234000
Name: Salary, dtype: int64

In [83]:
# Worst performing salesman on basis of total amount
data.groupby('SalesMan')['Sale_amt'].sum().sort_values()[:3]
# data.groupby('SalesMan')['Sale_amt'].sum().sort_values().head(3)

SalesMan
Stephen    21350.0
Shelli     33698.0
Karen      48204.0
Name: Sale_amt, dtype: float64

In [114]:
data.groupby('SalesMan')['Sale_amt'].aggregate(['sum', 'count', 'mean']).sort_values(by='count')

                sum  count          mean
SalesMan
Michael     66836.0      2  33418.000000
Karen       48204.0      3  16068.000000
Sigal      125037.5      3  41679.166667
John       167516.0      4  41879.000000
Shelli      33698.0      4   8424.500000
Diana       79300.0      4  19825.000000
Stephen     21350.0      5   4270.000000
Luis       101478.0      5  20295.600000
Steven     199690.0      5  39938.000000
David      212835.0      7  30405.000000
Alexander  233076.0      8  29134.500000

In [112]:
data.groupby(['Region','SalesMan'])['Units'].agg('mean').to_excel('test.xlsx')

In [115]:
data.groupby(['Region','SalesMan'])['Units'].agg('mean')

Region   SalesMan
Central  David        39.000000
         John         60.750000
         Luis         48.200000
         Shelli       48.250000
         Sigal        57.666667
         Steven       36.000000
East     Alexander    47.714286
         Diana        79.250000
         Karen        44.500000
West     Michael      44.500000
         Stephen      22.250000
Name: Units, dtype: float64

In [116]:
data.groupby(['Region','SalesMan'])['Units'].agg('mean')

Region   SalesMan
Central  David        39.000000
         John         60.750000
         Luis         48.200000
         Shelli       48.250000
         Sigal        57.666667
         Steven       36.000000
East     Alexander    47.714286
         Diana        79.250000
         Karen        44.500000
West     Michael      44.500000
         Stephen      22.250000
Name: Units, dtype: float64